In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\aparna\anaconda3\lib\site-packages (9.6.0)

In [2]:
import mysql.connector

conn = mysql.connector.connect(
    host="18.136.157.135",
    port=3306,
    user=" dm_team1",
    password="DM!$Team&279@20!",
    database="project_banking"
)

print("Connected Successfully!")

cursor = conn.cursor()
cursor.execute("SHOW TABLES;")

for table in cursor:
    print(table)

Connected Successfully!
('Cust_Account',)
('Cust_Demographics',)
('Cust_Enquiry',)

In [3]:
cursor.execute("SELECT * FROM Cust_Account LIMIT 5;")
rows = cursor.fetchall()

for row in rows:
    print(row)

('10-Nov-15', '12265', '20-Oct-15', '6', '1', '09-Jun-13', '30-Jun-14', '05-Jul-14', '30-Sep-15', '20900', '0', '', '"""STDSTDSTDXXXXXXXXXXXXXXXSTDXXXXXXXXXXXXXXXSTD"""', '', '01-Sep-15', '01-Jul-14', '', '', '', '', '')
('10-Nov-15', '12265', '20-Oct-15', '10', '1', '25-May-12', '06-Sep-15', '', '03-Oct-15', '16201', '10390', '', '"""000000000000000000000000000000000000000000000000000000"""', '"""000000000000000000000000000XXX000000000000000000000000"""', '01-Oct-15', '01-Nov-12', '14000', '1400', '', '3', '5603')
('10-Nov-15', '12265', '20-Oct-15', '10', '1', '22-Mar-12', '31-Aug-15', '', '30-Sep-15', '41028', '34420', '', '"""000000000000000000000000000000000000000000000000000000"""', '"""000000000000000000000000000000000000000000000000000000"""', '01-Sep-15', '01-Oct-12', '', '', '', '', '')
('20-Jul-15', '15606', '09-Jul-15', '10', '1', '13-Jan-06', '', '26-Jul-07', '31-Jan-09', '93473', '0', '', '"""120090060060060030000000000000000000000000000000000000"""', '', '01-Jul-07', '01-Feb-06', '', '', '', '', '')
('20-Jul-15', '15606', '09-Jul-15', '6', '1', '18-Jan-15', '05-May-15', '', '31-May-15', '20250', '13500', '', '"""000000000000000"""', '', '01-May-15', '01-Jan-15', '', '', '', '', '')

In [4]:
import pandas as pd

df_account = pd.read_sql("SELECT * FROM Cust_Account", conn)
df_enquiry = pd.read_sql("SELECT * FROM Cust_Enquiry", conn)
df_demo = pd.read_sql("SELECT * FROM Cust_Demographics", conn)

print(df_account.head())

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\4270682376.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_account = pd.read_sql("SELECT * FROM Cust_Account", conn)
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\4270682376.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_enquiry = pd.read_sql("SELECT * FROM Cust_Enquiry", conn)
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\4270682376.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_demo = pd.read_sql("SELECT * FROM Cust_Demographics", conn)

   dt_opened customer_no  upload_dt acct_type owner_indic  opened_dt  \
0  10-Nov-15       12265  20-Oct-15         6           1  09-Jun-13
1  10-Nov-15       12265  20-Oct-15        10           1  25-May-12
2  10-Nov-15       12265  20-Oct-15        10           1  22-Mar-12
3  20-Jul-15       15606  09-Jul-15        10           1  13-Jan-06
4  20-Jul-15       15606  09-Jul-15         6           1  18-Jan-15

  last_paymt_dt  closed_dt reporting_dt high_credit_amt  ... amt_past_due  \
0     30-Jun-14  05-Jul-14    30-Sep-15           20900  ...
1     06-Sep-15               03-Oct-15           16201  ...
2     31-Aug-15               30-Sep-15           41028  ...
3                26-Jul-07    31-Jan-09           93473  ...
4     05-May-15               31-May-15           20250  ...

                                     paymenthistory1  \
0  """STDSTDSTDXXXXXXXXXXXXXXXSTDXXXXXXXXXXXXXXXS...
1  """0000000000000000000000000000000000000000000...
2  """0000000000000000000000000000000000000000000...
3  """1200900600600600300000000000000000000000000...
4                              """000000000000000"""

                                     paymenthistory2 paymt_str_dt  \
0                                                       01-Sep-15
1  """000000000000000000000000000XXX0000000000000...    01-Oct-15
2  """0000000000000000000000000000000000000000000...    01-Sep-15
3                                                       01-Jul-07
4                                                       01-May-15

  paymt_end_dt creditlimit cashlimit rateofinterest paymentfrequency  \
0    01-Jul-14
1    01-Nov-12       14000      1400                               3
2    01-Oct-12
3    01-Feb-06
4    01-Jan-15

  actualpaymentamount
0
1                5603
2
3
4

[5 rows x 21 columns]

In [5]:
df_demo.to_csv("Cust_Demographics.csv", index=False)
df_account.to_csv("Cust_Account.csv", index=False)
df_enquiry.to_csv("Cust_Enquiry.csv", index=False)

In [6]:
import os
os.getcwd()

'C:\\Users\\APARNA\\Documents\\Client Project'

In [7]:
data1=pd.read_csv("Cust_Account.csv")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\2202858513.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  data1=pd.read_csv("Cust_Account.csv")

In [8]:
data1.head()

,dt_opened,customer_no,upload_dt,acct_type,owner_indic,opened_dt,last_paymt_dt,closed_dt,reporting_dt,high_credit_amt,...,amt_past_due,paymenthistory1,paymenthistory2,paymt_str_dt,paymt_end_dt,creditlimit,cashlimit,rateofinterest,paymentfrequency,actualpaymentamount
0,10-Nov-15,12265,20-Oct-15,6,1,09-Jun-13,30-Jun-14,05-Jul-14,30-Sep-15,20900.0,...,NaN,"""""""STDSTDSTDXXXXXXXXXXXXXXXSTDXXXXXXXXXXXXXXXS...",NaN,01-Sep-15,01-Jul-14,NaN,NaN,NaN,NaN,NaN
1,10-Nov-15,12265,20-Oct-15,10,1,25-May-12,06-Sep-15,NaN,03-Oct-15,16201.0,...,NaN,"""""""0000000000000000000000000000000000000000000...","""""""000000000000000000000000000XXX0000000000000...",01-Oct-15,01-Nov-12,14000.0,1400.0,NaN,3.0,5603.0
2,10-Nov-15,12265,20-Oct-15,10,1,22-Mar-12,31-Aug-15,NaN,30-Sep-15,41028.0,...,NaN,"""""""0000000000000000000000000000000000000000000...","""""""0000000000000000000000000000000000000000000...",01-Sep-15,01-Oct-12,NaN,NaN,NaN,NaN,NaN
3,20-Jul-15,15606,09-Jul-15,10,1,13-Jan-06,NaN,26-Jul-07,31-Jan-09,93473.0,...,NaN,"""""""1200900600600600300000000000000000000000000...",NaN,01-Jul-07,01-Feb-06,NaN,NaN,NaN,NaN,NaN
4,20-Jul-15,15606,09-Jul-15,6,1,18-Jan-15,05-May-15,NaN,31-May-15,20250.0,...,NaN,"""""""000000000000000""""""",NaN,01-May-15,01-Jan-15,NaN,NaN,NaN,NaN,NaN

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186329 entries, 0 to 186328
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_opened            186329 non-null  object
 1   customer_no          186329 non-null  int64
 2   upload_dt            186329 non-null  object
 3   acct_type            186329 non-null  int64
 4   owner_indic          186329 non-null  int64
 5   opened_dt            185874 non-null  object
 6   last_paymt_dt        160842 non-null  object
 7   closed_dt            77254 non-null   object
 8   reporting_dt         186329 non-null  object
 9   high_credit_amt      177454 non-null  float64
 10  cur_balance_amt      186329 non-null  int64
 11  amt_past_due         876 non-null     float64
 12  paymenthistory1      186329 non-null  object
 13  paymenthistory2      78505 non-null   object
 14  paymt_str_dt         186328 non-null  object
 15  paymt_end_dt         186328 non-null  object
 16  creditlimit          48852 non-null   float64
 17  cashlimit            35282 non-null   float64
 18  rateofinterest       24833 non-null   object
 19  paymentfrequency     63893 non-null   float64
 20  actualpaymentamount  41053 non-null   float64
dtypes: float64(6), int64(4), object(11)
memory usage: 29.9+ MB

In [10]:
date_cols = ["dt_opened","upload_dt","opened_dt","last_paymt_dt","closed_dt","reporting_dt"]

for col in date_cols:
    data1[col] = pd.to_datetime(data1[col], errors="coerce")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")

In [11]:
data1["opened_dt"].fillna(data1["dt_opened"], inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\4198326471.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["opened_dt"].fillna(data1["dt_opened"], inplace=True)

Some missing values are meaningful.
For example, if last_paymt_dt is missing, it may mean the customer never made a payment.

If I directly fill missing values, the model cannot tell which values were originally missing. That removes useful information.

So I did two steps:

Create a flag column (never_paid_flag) that stores whether the value was missing.

Fill missing values with a logical replacement (opened_dt) so calculations can still be done.

This way:

The dataset has no missing values (good for models)

The information that the value was missing is still preserved

So the model can learn patterns like:
customers who never paid → higher risk.

In [12]:
data1["never_paid_flag"] = data1["last_paymt_dt"].isnull().astype(int)
data1["last_paymt_dt"].fillna(data1["opened_dt"], inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\552062690.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["last_paymt_dt"].fillna(data1["opened_dt"], inplace=True)

In [13]:
data1["is_active_account"] = data1["closed_dt"].isnull().astype(int)
data1["closed_dt"].fillna(data1["reporting_dt"], inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_26116\3157574310.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["closed_dt"].fillna(data1["reporting_dt"], inplace=True)

In [13]:
data1["high_credit_amt"].fillna(0, inplace=True) # hign credit amount means Highest amount of credit customer ever used in that account

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1526886534.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["high_credit_amt"].fillna(0, inplace=True) # hign credit amount means Highest amount of credit customer ever used in that account

In [14]:
data1["amt_past_due"].fillna(0, inplace=True)
#Amount customer has not paid yet but should have paid.
#Because logically missing past due = customer has no overdue So replacing with 0 is correct.

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\199257729.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["amt_past_due"].fillna(0, inplace=True)

Missing values in creditlimit usually mean the account does not have a credit facility, not that the value is unknown.
So we fill missing values with 0 to represent “no credit limit”.

We also create a flag column (has_creditlimit) before filling so we don’t lose the original information about which values were missing.

This helps the model understand:

whether customer had credit access

how much credit they had

So we preserve information and keep data usable for modeling.

In [15]:
data1["has_creditlimit"] = data1["creditlimit"].notnull().astype(int)
data1["creditlimit"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1073089347.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["creditlimit"].fillna(0, inplace=True)

In [16]:
data1["has_cashlimit"] = data1["cashlimit"].notnull().astype(int)
data1["cashlimit"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\3146667054.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["cashlimit"].fillna(0, inplace=True)

In [17]:
data1["has_interest"] = data1["rateofinterest"].notnull().astype(int)
data1["rateofinterest"] = pd.to_numeric(data1["rateofinterest"], errors="coerce")
data1["rateofinterest"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\733417622.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["rateofinterest"].fillna(0, inplace=True)

In [18]:
data1["has_paymentfreq"] = data1["paymentfrequency"].notnull().astype(int)
data1["paymentfrequency"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\1705125091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["paymentfrequency"].fillna(0, inplace=True)

In [19]:
data1["has_payment"] = data1["actualpaymentamount"].notnull().astype(int)
data1["actualpaymentamount"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\2958655560.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["actualpaymentamount"].fillna(0, inplace=True)

In [20]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186329 entries, 0 to 186328
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_opened            186329 non-null  datetime64[ns]
 1   customer_no          186329 non-null  int64
 2   upload_dt            186329 non-null  datetime64[ns]
 3   acct_type            186329 non-null  int64
 4   owner_indic          186329 non-null  int64
 5   opened_dt            186329 non-null  datetime64[ns]
 6   last_paymt_dt        186329 non-null  datetime64[ns]
 7   closed_dt            77254 non-null   datetime64[ns]
 8   reporting_dt         186329 non-null  datetime64[ns]
 9   high_credit_amt      186329 non-null  float64
 10  cur_balance_amt      186329 non-null  int64
 11  amt_past_due         186329 non-null  float64
 12  paymenthistory1      186329 non-null  object
 13  paymenthistory2      78505 non-null   object
 14  paymt_str_dt         186328 non-null  object
 15  paymt_end_dt         186328 non-null  object
 16  creditlimit          186329 non-null  float64
 17  cashlimit            186329 non-null  float64
 18  rateofinterest       186329 non-null  float64
 19  paymentfrequency     186329 non-null  float64
 20  actualpaymentamount  186329 non-null  float64
 21  never_paid_flag      186329 non-null  int64
 22  has_creditlimit      186329 non-null  int64
 23  has_cashlimit        186329 non-null  int64
 24  has_interest         186329 non-null  int64
 25  has_paymentfreq      186329 non-null  int64
 26  has_payment          186329 non-null  int64
dtypes: datetime64[ns](6), float64(7), int64(10), object(4)
memory usage: 38.4+ MB

In [21]:
data2=pd.read_csv("Cust_Demographics.csv")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\2611541161.py:1: DtypeWarning: Columns (12,20,63) have mixed types. Specify dtype option on import or set low_memory=False.
  data2=pd.read_csv("Cust_Demographics.csv")

In [22]:
data2.head()

,dt_opened,customer_no,entry_time,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,Bad_label
0,18-Apr-15,1,13-Apr-15,Insignia,13-Apr-15,650.0,2.0,Card Setup,14.0,500000.0,...,21.0,R,NaN,NaN,0000-00-00,0.0,98332XXXXX,1.0,N,0
1,21-Apr-15,2,21-Apr-15,Insignia,21-Apr-15,760.0,1.0,Card Setup,14.0,1200000.0,...,17.0,R,NaN,NaN,0000-00-00,0.0,99455XXXXX,1.0,N,0
2,22-Apr-15,3,21-Apr-15,Insignia,21-Apr-15,774.0,1.0,Card Setup,14.0,700000.0,...,17.0,R,NaN,NaN,0000-00-00,0.0,98456XXXXX,1.0,N,0
3,25-Apr-15,4,15-Apr-15,Insignia,20-Apr-15,770.0,1.0,Card Setup,14.0,500000.0,...,21.0,R,NaN,NaN,6/15/65,1.0,98220XXXXX,1.0,N,0
4,06-May-15,5,30-Apr-15,Insignia,NaN,NaN,3.0,Card Setup,14.0,500000.0,...,13.0,R,NaN,NaN,0000-00-00,0.0,98111XXXXX,1.0,N,0

In [23]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 83 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  object
 1   customer_no  23896 non-null  int64
 2   entry_time   23881 non-null  object
 3   feature_1    23881 non-null  object
 4   feature_2    21060 non-null  object
 5   feature_3    21060 non-null  float64
 6   feature_4    23881 non-null  float64
 7   feature_5    23881 non-null  object
 8   feature_6    23881 non-null  float64
 9   feature_7    23881 non-null  float64
 10  feature_8    1261 non-null   object
 11  feature_9    1261 non-null   object
 12  feature_10   51 non-null     object
 13  feature_11   23881 non-null  object
 14  feature_12   23881 non-null  object
 15  feature_13   10892 non-null  object
 16  feature_14   16163 non-null  float64
 17  feature_15   23873 non-null  object
 18  feature_16   23869 non-null  object
 19  feature_17   1027 non-null   object
 20  feature_18   18 non-null     object
 21  feature_19   23881 non-null  float64
 22  feature_20   23896 non-null  object
 23  feature_21   23881 non-null  object
 24  feature_22   23896 non-null  object
 25  feature_23   23881 non-null  object
 26  feature_24   23256 non-null  object
 27  feature_25   23881 non-null  float64
 28  feature_26   23881 non-null  float64
 29  feature_27   20259 non-null  object
 30  feature_28   23881 non-null  object
 31  feature_29   23881 non-null  float64
 32  feature_30   23881 non-null  float64
 33  feature_31   23881 non-null  float64
 34  feature_32   23881 non-null  object
 35  feature_33   23881 non-null  object
 36  feature_34   23881 non-null  float64
 37  feature_35   23881 non-null  float64
 38  feature_36   18214 non-null  object
 39  feature_37   18214 non-null  object
 40  feature_38   18214 non-null  object
 41  feature_39   23881 non-null  float64
 42  feature_40   23881 non-null  float64
 43  feature_41   23881 non-null  float64
 44  feature_42   23881 non-null  float64
 45  feature_43   23881 non-null  object
 46  feature_44   23881 non-null  float64
 47  feature_45   10183 non-null  object
 48  feature_46   23802 non-null  object
 49  feature_47   23896 non-null  object
 50  feature_48   5497 non-null   object
 51  feature_49   104 non-null    float64
 52  feature_50   23881 non-null  object
 53  feature_51   12474 non-null  object
 54  feature_52   23881 non-null  float64
 55  feature_53   12286 non-null  object
 56  feature_54   23881 non-null  object
 57  feature_55   23881 non-null  float64
 58  feature_56   23881 non-null  float64
 59  feature_57   2393 non-null   object
 60  feature_58   23881 non-null  object
 61  feature_59   23881 non-null  object
 62  feature_60   23881 non-null  object
 63  feature_61   9 non-null      object
 64  feature_62   23881 non-null  object
 65  feature_63   23881 non-null  object
 66  feature_64   23881 non-null  float64
 67  feature_65   23881 non-null  float64
 68  feature_66   23881 non-null  float64
 69  feature_67   23881 non-null  float64
 70  feature_68   23881 non-null  float64
 71  feature_69   23881 non-null  float64
 72  feature_70   23881 non-null  object
 73  feature_71   23881 non-null  float64
 74  feature_72   23881 non-null  object
 75  feature_73   2945 non-null   object
 76  feature_74   17 non-null     float64
 77  feature_75   23881 non-null  object
 78  feature_76   23881 non-null  float64
 79  feature_77   23896 non-null  object
 80  feature_78   23881 non-null  float64
 81  feature_79   23881 non-null  object
 82  Bad_label    23896 non-null  int64
dtypes: float64(32), int64(2), object(49)
memory usage: 15.1+ MB

In [24]:
missing = data2.isnull().mean()*100
missing.sort_values(ascending=False)

feature_61    99.962337
feature_74    99.928858
feature_18    99.924674
feature_10    99.786575
feature_49    99.564781
                ...
feature_22     0.000000
feature_47     0.000000
feature_20     0.000000
feature_77     0.000000
Bad_label      0.000000
Length: 83, dtype: float64

In [25]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 83 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  object
 1   customer_no  23896 non-null  int64
 2   entry_time   23881 non-null  object
 3   feature_1    23881 non-null  object
 4   feature_2    21060 non-null  object
 5   feature_3    21060 non-null  float64
 6   feature_4    23881 non-null  float64
 7   feature_5    23881 non-null  object
 8   feature_6    23881 non-null  float64
 9   feature_7    23881 non-null  float64
 10  feature_8    1261 non-null   object
 11  feature_9    1261 non-null   object
 12  feature_10   51 non-null     object
 13  feature_11   23881 non-null  object
 14  feature_12   23881 non-null  object
 15  feature_13   10892 non-null  object
 16  feature_14   16163 non-null  float64
 17  feature_15   23873 non-null  object
 18  feature_16   23869 non-null  object
 19  feature_17   1027 non-null   object
 20  feature_18   18 non-null     object
 21  feature_19   23881 non-null  float64
 22  feature_20   23896 non-null  object
 23  feature_21   23881 non-null  object
 24  feature_22   23896 non-null  object
 25  feature_23   23881 non-null  object
 26  feature_24   23256 non-null  object
 27  feature_25   23881 non-null  float64
 28  feature_26   23881 non-null  float64
 29  feature_27   20259 non-null  object
 30  feature_28   23881 non-null  object
 31  feature_29   23881 non-null  float64
 32  feature_30   23881 non-null  float64
 33  feature_31   23881 non-null  float64
 34  feature_32   23881 non-null  object
 35  feature_33   23881 non-null  object
 36  feature_34   23881 non-null  float64
 37  feature_35   23881 non-null  float64
 38  feature_36   18214 non-null  object
 39  feature_37   18214 non-null  object
 40  feature_38   18214 non-null  object
 41  feature_39   23881 non-null  float64
 42  feature_40   23881 non-null  float64
 43  feature_41   23881 non-null  float64
 44  feature_42   23881 non-null  float64
 45  feature_43   23881 non-null  object
 46  feature_44   23881 non-null  float64
 47  feature_45   10183 non-null  object
 48  feature_46   23802 non-null  object
 49  feature_47   23896 non-null  object
 50  feature_48   5497 non-null   object
 51  feature_49   104 non-null    float64
 52  feature_50   23881 non-null  object
 53  feature_51   12474 non-null  object
 54  feature_52   23881 non-null  float64
 55  feature_53   12286 non-null  object
 56  feature_54   23881 non-null  object
 57  feature_55   23881 non-null  float64
 58  feature_56   23881 non-null  float64
 59  feature_57   2393 non-null   object
 60  feature_58   23881 non-null  object
 61  feature_59   23881 non-null  object
 62  feature_60   23881 non-null  object
 63  feature_61   9 non-null      object
 64  feature_62   23881 non-null  object
 65  feature_63   23881 non-null  object
 66  feature_64   23881 non-null  float64
 67  feature_65   23881 non-null  float64
 68  feature_66   23881 non-null  float64
 69  feature_67   23881 non-null  float64
 70  feature_68   23881 non-null  float64
 71  feature_69   23881 non-null  float64
 72  feature_70   23881 non-null  object
 73  feature_71   23881 non-null  float64
 74  feature_72   23881 non-null  object
 75  feature_73   2945 non-null   object
 76  feature_74   17 non-null     float64
 77  feature_75   23881 non-null  object
 78  feature_76   23881 non-null  float64
 79  feature_77   23896 non-null  object
 80  feature_78   23881 non-null  float64
 81  feature_79   23881 non-null  object
 82  Bad_label    23896 non-null  int64
dtypes: float64(32), int64(2), object(49)
memory usage: 15.1+ MB

In [26]:
data2["dt_opened"] = pd.to_datetime(data2["dt_opened"], errors="coerce")
data2["entry_time"] = pd.to_datetime(data2["entry_time"], errors="coerce")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\2978224859.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data2["dt_opened"] = pd.to_datetime(data2["dt_opened"], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\2978224859.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data2["entry_time"] = pd.to_datetime(data2["entry_time"], errors="coerce")

In [27]:
missing = data2.isnull().mean()*100
drop_cols = missing[missing > 60].index
data2.drop(columns=drop_cols, inplace=True)

In [29]:
const_cols = [col for col in data2.columns if data2[col].nunique() <= 1]
data2.drop(columns=const_cols, inplace=True)

In [28]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 72 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  datetime64[ns]
 1   customer_no  23896 non-null  int64
 2   entry_time   23881 non-null  datetime64[ns]
 3   feature_1    23881 non-null  object
 4   feature_2    21060 non-null  object
 5   feature_3    21060 non-null  float64
 6   feature_4    23881 non-null  float64
 7   feature_5    23881 non-null  object
 8   feature_6    23881 non-null  float64
 9   feature_7    23881 non-null  float64
 10  feature_11   23881 non-null  object
 11  feature_12   23881 non-null  object
 12  feature_13   10892 non-null  object
 13  feature_14   16163 non-null  float64
 14  feature_15   23873 non-null  object
 15  feature_16   23869 non-null  object
 16  feature_19   23881 non-null  float64
 17  feature_20   23896 non-null  object
 18  feature_21   23881 non-null  object
 19  feature_22   23896 non-null  object
 20  feature_23   23881 non-null  object
 21  feature_24   23256 non-null  object
 22  feature_25   23881 non-null  float64
 23  feature_26   23881 non-null  float64
 24  feature_27   20259 non-null  object
 25  feature_28   23881 non-null  object
 26  feature_29   23881 non-null  float64
 27  feature_30   23881 non-null  float64
 28  feature_31   23881 non-null  float64
 29  feature_32   23881 non-null  object
 30  feature_33   23881 non-null  object
 31  feature_34   23881 non-null  float64
 32  feature_35   23881 non-null  float64
 33  feature_36   18214 non-null  object
 34  feature_37   18214 non-null  object
 35  feature_38   18214 non-null  object
 36  feature_39   23881 non-null  float64
 37  feature_40   23881 non-null  float64
 38  feature_41   23881 non-null  float64
 39  feature_42   23881 non-null  float64
 40  feature_43   23881 non-null  object
 41  feature_44   23881 non-null  float64
 42  feature_45   10183 non-null  object
 43  feature_46   23802 non-null  object
 44  feature_47   23896 non-null  object
 45  feature_50   23881 non-null  object
 46  feature_51   12474 non-null  object
 47  feature_52   23881 non-null  float64
 48  feature_53   12286 non-null  object
 49  feature_54   23881 non-null  object
 50  feature_55   23881 non-null  float64
 51  feature_56   23881 non-null  float64
 52  feature_58   23881 non-null  object
 53  feature_59   23881 non-null  object
 54  feature_60   23881 non-null  object
 55  feature_62   23881 non-null  object
 56  feature_63   23881 non-null  object
 57  feature_64   23881 non-null  float64
 58  feature_65   23881 non-null  float64
 59  feature_66   23881 non-null  float64
 60  feature_67   23881 non-null  float64
 61  feature_68   23881 non-null  float64
 62  feature_69   23881 non-null  float64
 63  feature_70   23881 non-null  object
 64  feature_71   23881 non-null  float64
 65  feature_72   23881 non-null  object
 66  feature_75   23881 non-null  object
 67  feature_76   23881 non-null  float64
 68  feature_77   23896 non-null  object
 69  feature_78   23881 non-null  float64
 70  feature_79   23881 non-null  object
 71  Bad_label    23896 non-null  int64
dtypes: datetime64[ns](2), float64(30), int64(2), object(38)
memory usage: 13.1+ MB

In [29]:
# -------- NUMERIC COLUMNS --------
num_cols = data2.select_dtypes(include=["float64","int64"]).columns
data2[num_cols] = data2[num_cols].fillna(data2[num_cols].median())

In [30]:
# -------- CATEGORICAL COLUMNS --------
cat_cols = data2.select_dtypes(include="object").columns
data2[cat_cols] = data2[cat_cols].fillna("Missing")

In [31]:
# -------- DATE COLUMNS --------
date_cols = data2.select_dtypes(include="datetime64[ns]").columns
data2[date_cols] = data2[date_cols].fillna(pd.Timestamp("1900-01-01"))

In [32]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 72 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  datetime64[ns]
 1   customer_no  23896 non-null  int64
 2   entry_time   23896 non-null  datetime64[ns]
 3   feature_1    23896 non-null  object
 4   feature_2    23896 non-null  object
 5   feature_3    23896 non-null  float64
 6   feature_4    23896 non-null  float64
 7   feature_5    23896 non-null  object
 8   feature_6    23896 non-null  float64
 9   feature_7    23896 non-null  float64
 10  feature_11   23896 non-null  object
 11  feature_12   23896 non-null  object
 12  feature_13   23896 non-null  object
 13  feature_14   23896 non-null  float64
 14  feature_15   23896 non-null  object
 15  feature_16   23896 non-null  object
 16  feature_19   23896 non-null  float64
 17  feature_20   23896 non-null  object
 18  feature_21   23896 non-null  object
 19  feature_22   23896 non-null  object
 20  feature_23   23896 non-null  object
 21  feature_24   23896 non-null  object
 22  feature_25   23896 non-null  float64
 23  feature_26   23896 non-null  float64
 24  feature_27   23896 non-null  object
 25  feature_28   23896 non-null  object
 26  feature_29   23896 non-null  float64
 27  feature_30   23896 non-null  float64
 28  feature_31   23896 non-null  float64
 29  feature_32   23896 non-null  object
 30  feature_33   23896 non-null  object
 31  feature_34   23896 non-null  float64
 32  feature_35   23896 non-null  float64
 33  feature_36   23896 non-null  object
 34  feature_37   23896 non-null  object
 35  feature_38   23896 non-null  object
 36  feature_39   23896 non-null  float64
 37  feature_40   23896 non-null  float64
 38  feature_41   23896 non-null  float64
 39  feature_42   23896 non-null  float64
 40  feature_43   23896 non-null  object
 41  feature_44   23896 non-null  float64
 42  feature_45   23896 non-null  object
 43  feature_46   23896 non-null  object
 44  feature_47   23896 non-null  object
 45  feature_50   23896 non-null  object
 46  feature_51   23896 non-null  object
 47  feature_52   23896 non-null  float64
 48  feature_53   23896 non-null  object
 49  feature_54   23896 non-null  object
 50  feature_55   23896 non-null  float64
 51  feature_56   23896 non-null  float64
 52  feature_58   23896 non-null  object
 53  feature_59   23896 non-null  object
 54  feature_60   23896 non-null  object
 55  feature_62   23896 non-null  object
 56  feature_63   23896 non-null  object
 57  feature_64   23896 non-null  float64
 58  feature_65   23896 non-null  float64
 59  feature_66   23896 non-null  float64
 60  feature_67   23896 non-null  float64
 61  feature_68   23896 non-null  float64
 62  feature_69   23896 non-null  float64
 63  feature_70   23896 non-null  object
 64  feature_71   23896 non-null  float64
 65  feature_72   23896 non-null  object
 66  feature_75   23896 non-null  object
 67  feature_76   23896 non-null  float64
 68  feature_77   23896 non-null  object
 69  feature_78   23896 non-null  float64
 70  feature_79   23896 non-null  object
 71  Bad_label    23896 non-null  int64
dtypes: datetime64[ns](2), float64(30), int64(2), object(38)
memory usage: 13.1+ MB

In [33]:
data3=pd.read_csv("Cust_Enquiry.csv")

In [34]:
data3.head()

   dt_opened  customer_no  upload_dt enquiry_dt  enq_purpose    enq_amt
0  18-Apr-15            1  21-Apr-15  19-Dec-14          2.0  3500000.0
1  18-Apr-15            1  21-Apr-15  05-Mar-14          5.0   500000.0
2  18-Apr-15            1  21-Apr-15  05-Mar-14          0.0    50000.0
3  18-Apr-15            1  21-Apr-15  22-Feb-14         10.0    50000.0
4  18-Apr-15            1  21-Apr-15  11-Jun-13         10.0     1000.0

In [40]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413188 entries, 0 to 413187
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   dt_opened    413188 non-null  datetime64[ns]
 1   customer_no  413188 non-null  int64
 2   upload_dt    413078 non-null  datetime64[ns]
 3   enquiry_dt   413078 non-null  datetime64[ns]
 4   enq_purpose  413188 non-null  float64
 5   enq_amt      413188 non-null  float64
dtypes: datetime64[ns](3), float64(2), int64(1)
memory usage: 18.9 MB

In [41]:
data3["dt_opened"] = pd.to_datetime(data3["dt_opened"], errors="coerce")
data3["upload_dt"] = pd.to_datetime(data3["upload_dt"], errors="coerce")
data3["enquiry_dt"] = pd.to_datetime(data3["enquiry_dt"], errors="coerce")

In [42]:
num_cols = data3.select_dtypes(include=["float64","int64"]).columns
data3[num_cols] = data3[num_cols].fillna(data3[num_cols].median())

cat_cols = data3.select_dtypes(include="object").columns
data3[cat_cols] = data3[cat_cols].fillna("Missing")

In [43]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413188 entries, 0 to 413187
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   dt_opened    413188 non-null  datetime64[ns]
 1   customer_no  413188 non-null  int64
 2   upload_dt    413078 non-null  datetime64[ns]
 3   enquiry_dt   413078 non-null  datetime64[ns]
 4   enq_purpose  413188 non-null  float64
 5   enq_amt      413188 non-null  float64
dtypes: datetime64[ns](3), float64(2), int64(1)
memory usage: 18.9 MB

In [44]:
enq= data3.groupby("customer_no").agg(
    total_enquiries=("enquiry_dt","count"),
    avg_enq_amt=("enq_amt","mean"),
    max_enq_amt=("enq_amt","max"),
    last_enq_date=("enquiry_dt","max")
).reset_index()

In [45]:
enq.head()

   customer_no  total_enquiries   avg_enq_amt  max_enq_amt last_enq_date
0            1               18  2.767306e+05    3500000.0    2014-12-19
1            2               68  9.818650e+07  750000000.0    2015-02-11
2            3                1  3.400000e+06    3400000.0    2014-02-08
3            4               34  1.494412e+06    4000000.0    2014-03-03
4            5                2  1.000000e+03       1000.0    2012-03-28

In [46]:
enq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_no      23896 non-null  int64
 1   total_enquiries  23896 non-null  int64
 2   avg_enq_amt      23896 non-null  float64
 3   max_enq_amt      23896 non-null  float64
 4   last_enq_date    23787 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 933.6 KB

In [47]:
acc = data1.groupby("customer_no").agg(  #aggregating account table
    total_accounts=("acct_type","count"),
    total_balance=("cur_balance_amt","sum"),
    avg_balance=("cur_balance_amt","mean"),
    total_past_due=("amt_past_due","sum"),
    max_credit=("high_credit_amt","max"),
    avg_credit=("high_credit_amt","mean")
).reset_index()

In [48]:
df = data2.merge(acc, on="customer_no", how="left")

In [49]:
df = df.merge(enq, on="customer_no", how="left")

In [50]:
df.head()

,dt_opened,customer_no,entry_time,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,total_accounts,total_balance,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,last_enq_date
0,2015-04-18,1,2015-04-13,Insignia,13-Apr-15,650.0,2.0,Card Setup,14.0,500000.0,...,18,4714857,261936.500000,2538209.0,2528846.0,4.388924e+05,18,2.767306e+05,3500000.0,2014-12-19
1,2015-04-21,2,2015-04-21,Insignia,21-Apr-15,760.0,1.0,Card Setup,14.0,1200000.0,...,2,30754,15377.000000,0.0,1000000.0,5.587975e+05,68,9.818650e+07,750000000.0,2015-02-11
2,2015-04-22,3,2015-04-21,Insignia,21-Apr-15,774.0,1.0,Card Setup,14.0,700000.0,...,1,17864,17864.000000,0.0,121523.0,1.215230e+05,1,3.400000e+06,3400000.0,2014-02-08
3,2015-04-25,4,2015-04-15,Insignia,20-Apr-15,770.0,1.0,Card Setup,14.0,500000.0,...,17,1845569,108562.882353,0.0,3000000.0,7.238038e+05,34,1.494412e+06,4000000.0,2014-03-03
4,2015-05-06,5,2015-04-30,Insignia,Missing,721.0,3.0,Card Setup,14.0,500000.0,...,7,7973,1139.000000,0.0,12662938.0,1.831072e+06,2,1.000000e+03,1000.0,2012-03-28

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   dt_opened        23896 non-null  datetime64[ns]
 1   customer_no      23896 non-null  int64
 2   entry_time       23896 non-null  datetime64[ns]
 3   feature_1        23896 non-null  object
 4   feature_2        23896 non-null  object
 5   feature_3        23896 non-null  float64
 6   feature_4        23896 non-null  float64
 7   feature_5        23896 non-null  object
 8   feature_6        23896 non-null  float64
 9   feature_7        23896 non-null  float64
 10  feature_11       23896 non-null  object
 11  feature_12       23896 non-null  object
 12  feature_13       23896 non-null  object
 13  feature_14       23896 non-null  float64
 14  feature_15       23896 non-null  object
 15  feature_16       23896 non-null  object
 16  feature_19       23896 non-null  float64
 17  feature_20       23896 non-null  object
 18  feature_21       23896 non-null  object
 19  feature_22       23896 non-null  object
 20  feature_23       23896 non-null  object
 21  feature_24       23896 non-null  object
 22  feature_25       23896 non-null  float64
 23  feature_26       23896 non-null  float64
 24  feature_27       23896 non-null  object
 25  feature_28       23896 non-null  object
 26  feature_29       23896 non-null  float64
 27  feature_30       23896 non-null  float64
 28  feature_31       23896 non-null  float64
 29  feature_32       23896 non-null  object
 30  feature_33       23896 non-null  object
 31  feature_34       23896 non-null  float64
 32  feature_35       23896 non-null  float64
 33  feature_36       23896 non-null  object
 34  feature_37       23896 non-null  object
 35  feature_38       23896 non-null  object
 36  feature_39       23896 non-null  float64
 37  feature_40       23896 non-null  float64
 38  feature_41       23896 non-null  float64
 39  feature_42       23896 non-null  float64
 40  feature_43       23896 non-null  object
 41  feature_44       23896 non-null  float64
 42  feature_45       23896 non-null  object
 43  feature_46       23896 non-null  object
 44  feature_47       23896 non-null  object
 45  feature_50       23896 non-null  object
 46  feature_51       23896 non-null  object
 47  feature_52       23896 non-null  float64
 48  feature_53       23896 non-null  object
 49  feature_54       23896 non-null  object
 50  feature_55       23896 non-null  float64
 51  feature_56       23896 non-null  float64
 52  feature_58       23896 non-null  object
 53  feature_59       23896 non-null  object
 54  feature_60       23896 non-null  object
 55  feature_62       23896 non-null  object
 56  feature_63       23896 non-null  object
 57  feature_64       23896 non-null  float64
 58  feature_65       23896 non-null  float64
 59  feature_66       23896 non-null  float64
 60  feature_67       23896 non-null  float64
 61  feature_68       23896 non-null  float64
 62  feature_69       23896 non-null  float64
 63  feature_70       23896 non-null  object
 64  feature_71       23896 non-null  float64
 65  feature_72       23896 non-null  object
 66  feature_75       23896 non-null  object
 67  feature_76       23896 non-null  float64
 68  feature_77       23896 non-null  object
 69  feature_78       23896 non-null  float64
 70  feature_79       23896 non-null  object
 71  Bad_label        23896 non-null  int64
 72  total_accounts   23896 non-null  int64
 73  total_balance    23896 non-null  int64
 74  avg_balance      23896 non-null  float64
 75  total_past_due   23896 non-null  float64
 76  max_credit       23896 non-null  float64
 77  avg_credit       23896 non-null  float64
 78  total_enquiries  23896 non-null  int64
 79  avg_enq_amt      23896 non-null  float64
 80  max_enq_amt      23896 non-null  float64
 81  last_enq_date    23787 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(36), int64(5), object(38)
memory usage: 14.9+ MB

In [52]:
 today = pd.Timestamp.today()#Dates cannot go into model directly.

df["account_age_days"] = (today - df["dt_opened"]).dt.days
df["customer_tenure_days"] = (today - df["entry_time"]).dt.days
df["days_since_last_enq"] = (today - df["last_enq_date"]).dt.days

In [53]:
df["days_since_last_enq"].fillna(9999, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_16636\2094388345.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["days_since_last_enq"].fillna(9999, inplace=True)

In [54]:
df.drop(columns=["dt_opened","entry_time","last_enq_date"], inplace=True)

In [55]:
df.drop(columns=["customer_no"], inplace=True)

In [56]:
df.columns

Index(['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5',
       'feature_6', 'feature_7', 'feature_11', 'feature_12', 'feature_13',
       'feature_14', 'feature_15', 'feature_16', 'feature_19', 'feature_20',
       'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25',
       'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30',
       'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35',
       'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40',
       'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45',
       'feature_46', 'feature_47', 'feature_50', 'feature_51', 'feature_52',
       'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_58',
       'feature_59', 'feature_60', 'feature_62', 'feature_63', 'feature_64',
       'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69',
       'feature_70', 'feature_71', 'feature_72', 'feature_75', 'feature_76',
       'feature_77', 'feature_78', 'feature_79', 'Bad_label', 'total_accounts',
       'total_balance', 'avg_balance', 'total_past_due', 'max_credit',
       'avg_credit', 'total_enquiries', 'avg_enq_amt', 'max_enq_amt',
       'account_age_days', 'customer_tenure_days', 'days_since_last_enq'],
      dtype='object')

total_accounts: How many active credit accounts customer has.
total_balance: Total outstanding balance.
avg_balance: Balance per customer
total_past_due: Total overdue amount.
max_credit: Highest credit limit across accounts.
avg_credit: Highest credit limit across accounts.
total_enquiries: Number of times customer applied for credit.
avg_enq_amount: Average requested loan amount..
max_enq_amount: Largest loan requested.
days_since_last_enq: Recency of last credit enquiry.

##EDA

In [57]:
df["Bad_label"].value_counts()
df["Bad_label"].value_counts(normalize=True)
#Dataset is highly imbalanced with only 4.2% bad customers.

Bad_label
0    0.957985
1    0.042015
Name: proportion, dtype: float64

In [58]:
df.describe()

,feature_3,feature_4,feature_6,feature_7,feature_14,feature_19,feature_25,feature_26,feature_29,feature_30,...,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq
count,23896.000000,23896.000000,23896.0,2.389600e+04,23896.000000,23896.000000,23896.000000,23896.000000,23896.000000,23896.000000,...,2.389600e+04,2.389600e+04,2.389600e+04,2.389600e+04,23896.000000,2.389600e+04,2.389600e+04,23896.000000,23896.000000,23896.000000
mean,722.970581,2.322020,14.0,1.190610e+05,9.353030,1.049381,1.233763,0.725184,217552.732968,2001.186391,...,7.082324e+04,9.469535e+02,5.712405e+05,1.374346e+05,17.286491,5.483429e+05,7.231267e+06,3820.394459,3874.574824,4009.862027
std,35.041620,0.892719,0.0,7.750007e+04,4.975764,0.216666,0.423232,1.124780,159239.881327,11.990042,...,2.152128e+05,4.139207e+04,2.043482e+06,3.910046e+05,15.253240,3.086798e+06,4.162499e+07,68.600944,1060.110829,472.130200
min,-1.000000,1.000000,14.0,0.000000e+00,0.000000,1.000000,1.000000,0.000000,110001.000000,1964.000000,...,-1.165763e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000e+00,1.000000e+00,3716.000000,3724.000000,3724.000000
25%,700.000000,1.000000,14.0,7.200000e+04,12.000000,1.000000,1.000000,0.000000,110051.000000,1991.000000,...,9.083621e+03,0.000000e+00,7.043950e+04,3.914831e+04,7.000000,4.183333e+04,1.000000e+05,3761.000000,3791.000000,3852.000000
50%,721.000000,3.000000,14.0,1.040000e+05,12.000000,1.000000,1.000000,0.000000,110094.000000,2005.000000,...,2.596633e+04,0.000000e+00,1.863780e+05,6.981382e+04,13.000000,9.055286e+04,4.000000e+05,3810.000000,3843.000000,3929.000000
75%,741.000000,3.000000,14.0,1.390000e+05,12.000000,1.000000,1.000000,2.000000,390002.000000,2011.000000,...,6.346017e+04,0.000000e+00,4.600000e+05,1.328318e+05,23.000000,2.089790e+05,1.004940e+06,3875.000000,3903.000000,4029.000000
max,896.000000,3.000000,14.0,1.217000e+06,12.000000,2.000000,2.000000,10.000000,712245.000000,2015.000000,...,1.172659e+07,4.869309e+06,1.800000e+08,3.366662e+07,308.000000,1.709149e+08,1.000000e+09,3975.000000,46083.000000,9999.000000

In [59]:
df.groupby("Bad_label")["total_past_due"].mean()

Bad_label
0    964.179364
1    554.191235
Name: total_past_due, dtype: float64

In [60]:
df.groupby("Bad_label")["total_enquiries"].mean()

Bad_label
0    17.296829
1    17.050797
Name: total_enquiries, dtype: float64

In [61]:
df.groupby("Bad_label")["days_since_last_enq"].mean()

Bad_label
0    4010.817491
1    3988.076693
Name: days_since_last_enq, dtype: float64

In [62]:
df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_11,feature_12,feature_13,...,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq
0,Insignia,13-Apr-15,650.0,2.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,261936.500000,2538209.0,2528846.0,4.388924e+05,18,2.767306e+05,3500000.0,3973,3978,4093.0
1,Insignia,21-Apr-15,760.0,1.0,Card Setup,14.0,1200000.0,Y,IS1,Missing,...,15377.000000,0.0,1000000.0,5.587975e+05,68,9.818650e+07,750000000.0,3970,3970,4039.0
2,Insignia,21-Apr-15,774.0,1.0,Card Setup,14.0,700000.0,Y,IS1,Missing,...,17864.000000,0.0,121523.0,1.215230e+05,1,3.400000e+06,3400000.0,3969,3970,4407.0
3,Insignia,20-Apr-15,770.0,1.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,108562.882353,0.0,3000000.0,7.238038e+05,34,1.494412e+06,4000000.0,3966,3976,4384.0
4,Insignia,Missing,721.0,3.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,1139.000000,0.0,12662938.0,1.831072e+06,2,1.000000e+03,1000.0,3955,3961,5089.0

In [63]:
df.corr(numeric_only=True)

,feature_3,feature_4,feature_6,feature_7,feature_14,feature_19,feature_25,feature_26,feature_29,feature_30,...,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq
feature_3,1.000000,-0.244546,NaN,0.300612,0.000409,0.036544,-0.107900,0.031748,-0.013415,-0.054855,...,0.119278,-0.023734,0.119605,0.125145,-0.050376,0.078184,0.064036,-0.003184,-0.001691,0.130331
feature_4,-0.244546,1.000000,NaN,-0.092159,0.090714,-0.026393,0.028709,0.186957,-0.152153,0.036611,...,-0.010353,0.000599,-0.014473,-0.013638,0.033919,-0.026382,-0.020338,0.375516,0.046469,0.042981
feature_6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
feature_7,0.300612,-0.092159,NaN,1.000000,-0.007433,-0.018849,-0.126479,0.086991,0.044309,-0.061531,...,0.038982,0.033921,0.110120,0.082685,0.099182,0.105218,0.091079,0.067054,-0.000671,0.066470
feature_14,0.000409,0.090714,NaN,-0.007433,1.000000,-0.022227,0.002186,-0.005523,-0.412585,-0.031041,...,-0.035152,-0.018833,-0.046772,-0.040784,-0.056699,-0.044757,-0.037288,0.071921,0.019090,0.009056
feature_19,0.036544,-0.026393,NaN,-0.018849,-0.022227,1.000000,0.016502,-0.045115,-0.017425,0.033750,...,0.037417,-0.003309,0.014271,0.032232,-0.069762,0.004657,-0.008332,-0.012258,-0.006830,0.043867
feature_25,-0.107900,0.028709,NaN,-0.126479,0.002186,0.016502,1.000000,-0.248867,-0.044356,0.054272,...,-0.036699,-0.010923,-0.073728,-0.057798,-0.155268,-0.053276,-0.059211,-0.039829,-0.016409,-0.043479
feature_26,0.031748,0.186957,NaN,0.086991,-0.005523,-0.045115,-0.248867,1.000000,0.088713,-0.029610,...,0.012969,0.037638,0.039062,0.026982,0.095899,0.028855,0.031741,0.551933,0.018342,0.099929
feature_29,-0.013415,-0.152153,NaN,0.044309,-0.412585,-0.017425,-0.044356,0.088713,1.000000,0.077398,...,0.027376,0.021759,0.042114,0.030840,0.140175,0.041952,0.044951,-0.041371,-0.021031,-0.025967
feature_30,-0.054855,0.036611,NaN,-0.061531,-0.031041,0.033750,0.054272,-0.029610,0.077398,1.000000,...,0.022911,-0.009192,-0.014290,-0.005490,0.005555,-0.034174,-0.029550,0.001837,0.008662,-0.038673
feature_31,0.004234,-0.222876,NaN,-0.023632,-0.040439,0.011191,0.007362,-0.167786,-0.019985,-0.006384,...,0.014585,-0.005545,0.005593,0.008841,-0.031489,-0.005661,-0.010568,-0.377772,-0.031930,-0.056622
feature_34,0.110020,-0.074237,NaN,0.113484,0.008497,0.029353,-0.101519,0.014501,-0.006451,-0.211073,...,0.063417,0.009357,0.083705,0.086499,0.013797,0.073052,0.047148,-0.041427,-0.017118,0.028056
feature_35,0.052250,0.004941,NaN,0.091290,-0.041926,-0.003764,-0.027017,0.057395,0.080470,0.013549,...,0.036592,0.009008,0.053590,0.044696,0.043002,0.049629,0.030412,0.052105,0.002467,0.034192
feature_39,-0.109355,0.074801,NaN,-0.113239,-0.009130,-0.029140,0.102879,-0.013954,0.007195,0.212626,...,-0.060219,-0.009514,-0.080228,-0.082939,-0.015373,-0.072583,-0.047959,0.042341,0.017230,-0.027733
feature_40,-0.077983,0.000208,NaN,-0.078877,-0.066176,-0.014977,0.081007,-0.029631,0.082182,0.156723,...,-0.029476,-0.003439,-0.046146,-0.046419,0.003552,-0.042194,-0.022855,-0.041119,-0.011827,-0.032270
feature_41,-0.006529,0.027442,NaN,0.013453,-0.026739,-0.037409,-0.131980,0.100491,0.069432,0.117605,...,-0.026928,-0.000617,-0.015886,-0.032598,0.110577,-0.023499,0.009777,0.069869,0.006447,0.012973
feature_42,-0.041024,0.018673,NaN,-0.042683,0.004551,-0.006595,0.097925,-0.047998,-0.005961,0.051861,...,-0.011449,-0.003138,-0.019672,-0.016191,-0.032173,-0.020330,-0.020870,-0.024400,-0.005520,-0.013766
feature_44,-0.018789,-0.149460,NaN,0.039723,-0.407595,-0.018501,-0.033898,0.085234,0.983204,0.076640,...,0.023055,0.020843,0.038168,0.026837,0.137847,0.040679,0.044195,-0.040672,-0.020030,-0.025799
feature_52,0.056958,0.062276,NaN,0.573739,0.011326,-0.039237,-0.058729,0.110838,0.049173,-0.049564,...,-0.000871,-0.002883,0.068645,0.030638,0.119555,0.038373,0.049158,0.139577,0.004689,0.047344
feature_55,0.038684,-0.026692,NaN,-0.009875,-0.026364,0.918357,-0.039841,-0.032897,-0.015149,0.038677,...,0.043392,-0.002936,0.029725,0.042070,-0.065577,0.006471,-0.005122,-0.010471,-0.006546,0.046273
feature_56,0.056112,0.014438,NaN,0.024565,-0.008532,-0.007106,-0.027137,0.047401,0.088064,0.047992,...,0.072340,0.022276,0.060214,0.060647,0.024024,0.034352,0.025909,0.004106,-0.008983,-0.001982
feature_64,0.028380,0.043182,NaN,-0.000851,0.036222,-0.012418,0.004380,0.026892,-0.022602,0.141263,...,0.048343,0.016693,0.034634,0.036369,-0.001866,0.016797,0.009050,0.011021,-0.010223,-0.006601
feature_65,-0.038780,0.076695,NaN,-0.056591,0.073241,-0.022052,0.028327,-0.012500,-0.152658,0.128527,...,-0.027152,-0.004581,-0.043575,-0.034980,-0.052982,-0.029978,-0.027975,-0.012062,-0.000241,-0.009095
feature_66,-0.057687,-0.073999,NaN,-0.007093,-0.241405,-0.047027,0.009110,0.042741,0.650677,0.235309,...,-0.001408,0.012972,0.001230,-0.002769,0.075035,0.014180,0.018567,-0.014722,-0.019323,-0.036270
feature_67,-0.064111,0.085263,NaN,-0.060804,0.137769,-0.037576,0.071602,-0.029461,-0.200882,0.359842,...,-0.029578,-0.007860,-0.047346,-0.036762,-0.051890,-0.035047,-0.036889,0.050835,-0.007792,-0.021649
feature_68,0.110020,-0.074237,NaN,0.113484,0.008497,0.029353,-0.101519,0.014501,-0.006451,-0.211073,...,0.063417,0.009357,0.083705,0.086499,0.013797,0.073052,0.047148,-0.041427,-0.017118,0.028056
feature_69,0.052250,0.004941,NaN,0.091290,-0.041926,-0.003764,-0.027017,0.057395,0.080470,0.013549,...,0.036592,0.009008,0.053590,0.044696,0.043002,0.049629,0.030412,0.052105,0.002467,0.034192
feature_71,0.029551,0.032572,NaN,0.000597,0.035512,-0.008847,0.023313,0.022745,-0.049596,0.033412,...,0.049396,0.015668,0.038480,0.038668,0.006507,0.023925,0.017538,0.009269,-0.010853,0.000542
feature_76,-0.008012,-0.018708,NaN,0.048119,-0.036781,0.010217,-0.013503,0.013814,0.022407,-0.010196,...,0.018009,0.049530,0.036517,0.034664,0.008064,0.018773,0.009470,-0.001052,-0.001309,0.002511
feature_78,-0.005501,0.024352,NaN,-0.009618,-0.062174,0.003474,0.010019,0.017826,0.028278,0.051184,...,0.000286,-0.003253,-0.005070,-0.005270,-0.001584,-0.005452,-0.004353,0.044720,-0.001922,0.012593
Bad_label,-0.042356,0.017219,NaN,-0.059403,0.010797,0.005220,0.021835,-0.024310,-0.018638,0.006487,...,0.011809,-0.001987,0.010051,0.014456,-0.003236,0.004330,-0.004213,-0.016724,0.002384,-0.009664
total_accounts,0.060161,-0.005186,NaN,0.227343,-0.083848,-0.053639,-0.205477,0.132284,0.184831,-0.087132,...,0.030069,0.034825,0.218533,0.088430,0.710289,0.103071,0.193716,0.075138,0.008877,-0.056303
total_balance,0.087909,-0.001892,NaN,0.066670,-0.047937,0.007141,-0.069024,0.038352,0.046766,-0.010718,...,0.753883,0.044828,0.884130,0.784480,0.237452,0.248717,0.181042,0.015204,-0.000347,-0.023996
avg_balance,0.119278,-0.010353,NaN,0.038982,-0.035152,0.037417,-0.036699,0.012969,0.027376,0.022911,...,1.000000,0.023990,0.726009,0.862908,0.064146,0.204669,0.108060,0.001519,-0.002865,-0.011193
total_past_due,-0.023734,0.000599,NaN,0.033921,-0.018833,-0.003309,-0.010923,0.037638,0.021759,-0.009192,...,0.023990,1.000000,0.032063,0.020356,0.028241,0.020751,0.009969,0.007071,-0.000132,0.000130
max_credit,0.119605,-0.014473,NaN,0.110120,-0.046772,0.014271,-0.073728,0.039062,0.042114,-0.014290,...,0.726009,0.032063,1.000000,0.895030,0.190053,0.307272,0.210500,0.015666,0.002539,-0.011540
avg_credit,0.125145,-0.013638,NaN,0.082685,-0.040784,0.032232,-0.057798,0.026982,0.030840,-0.005490,...,0.862908,0.020356,0.895030,1.000000,0.106150,0.282864,0.170055,0.010268,-0.000225,-0.002721
total_enquiries,-0.050376,0.033919,NaN,0.099182,-0.056699,-0.069762,-0.155268,0.095899,0.140175,0.005555,...,0.064146,0.028241,0.190053,0.106150,1.000000,0.103013,0.210335,0.082664,0.014487,-0.142568
avg_enq_amt,0.078184,-0.026382,NaN,0.105218,-0.044757,0.004657,-0.053276,0.028855,0.041952,-0.034174,...,0.204669,0.020751,0.307272,0.282864,0.103013,1.000000,0.761236,0.011643,0.000583,0.005568
max_enq_amt,0.064036,-0.020338,NaN,0.091079,-0.037288,-0.008332,-0.059211,0.031741,0.044951,-0.029550,...,0.108060,0.009969,0.210500,0.170055,0.210335,0.761236,1.000000,0.014429,0.004871,-0.004861
account_age_days,-0.003184,0.375516,NaN,0.067054,0.071921,-0.012258,-0.039829,0.551933,-0.041371,0.001837,...,0.001519,0.007071,0.015666,0.010268,0.082664,0.011643,0.014429,1.000000,0.057775,0.145012
customer_tenure_days,-0.001691,0.046469,NaN,-0.000671,0.019090,-0.006830,-0.016409,0.018342,-0.021031,0.008662,...,-0.002865,-0.000132,0.002539,-0.000225,0.014487,0.000583,0.004871,0.057775,1.000000,0.004701
days_since_last_enq,0.130331,0.042981,NaN,0.066470,0.009056,0.043867,-0.043479,0.099929,-0.025967,-0.038673,...,-0.011193,0.000130,-0.011540,-0.002721,-0.142568,0.005568,-0.004861,0.145012,0.004701,1.000000

In [83]:
df['utilization_ratio'] = df['avg_balance'] / (df['max_credit'] + 1)
df['past_due_ratio'] = df['total_past_due'] / (df['max_credit'] + 1)
df['enquiry_rate'] = df['total_enquiries'] / (df['account_age_days'] + 1)
df['credit_intensity'] = df['avg_credit'] / (df['max_credit'] + 1)
df['tenure_ratio'] = df['customer_tenure_days'] / (df['account_age_days'] + 1)

In [84]:
df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_11,feature_12,feature_13,...,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq,utilization_ratio,past_due_ratio,enquiry_rate,credit_intensity,tenure_ratio
0,Insignia,13-Apr-15,650.0,2.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,2.767306e+05,3500000.0,3973,3978,4093.0,0.103579,1.003702,0.004529,0.173554,1.001007
1,Insignia,21-Apr-15,760.0,1.0,Card Setup,14.0,1200000.0,Y,IS1,Missing,...,9.818650e+07,750000000.0,3970,3970,4039.0,0.015377,0.000000,0.017124,0.558797,0.999748
2,Insignia,21-Apr-15,774.0,1.0,Card Setup,14.0,700000.0,Y,IS1,Missing,...,3.400000e+06,3400000.0,3969,3970,4407.0,0.147000,0.000000,0.000252,0.999992,1.000000
3,Insignia,20-Apr-15,770.0,1.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,1.494412e+06,4000000.0,3966,3976,4384.0,0.036188,0.000000,0.008571,0.241268,1.002269
4,Insignia,Missing,721.0,3.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,1.000000e+03,1000.0,3955,3961,5089.0,0.000090,0.000000,0.000506,0.144601,1.001264

In [91]:
X=df.drop("Bad_label", axis=1)
y=df["Bad_label"]

In [92]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [93]:
numeric_features = X.select_dtypes(include=['int64','float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

In [86]:
# categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
# numeric_cols = X.select_dtypes(include=['int64','float64']).columns.tolist()

In [87]:
categorical_cols

['feature_1',
 'feature_2',
 'feature_5',
 'feature_11',
 'feature_12',
 'feature_13',
 'feature_15',
 'feature_16',
 'feature_20',
 'feature_21',
 'feature_22',
 'feature_23',
 'feature_24',
 'feature_27',
 'feature_28',
 'feature_32',
 'feature_33',
 'feature_36',
 'feature_37',
 'feature_38',
 'feature_43',
 'feature_45',
 'feature_46',
 'feature_47',
 'feature_50',
 'feature_51',
 'feature_53',
 'feature_54',
 'feature_58',
 'feature_59',
 'feature_60',
 'feature_62',
 'feature_63',
 'feature_70',
 'feature_72',
 'feature_75',
 'feature_77',
 'feature_79']

In [94]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [95]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

In [96]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['feature_3', 'feature_4', 'feature_6',
                                  'feature_7', 'feature_14', 'feature_19',
                                  'feature_25', 'feature_26', 'feature_29',
                                  'feature_30', 'feature_31', 'feature_34',
                                  'feature_35', 'feature_39', 'feature_40',
                                  'feature_41', 'feature_42', 'feature_44',
                                  'feature_52', 'feature_55', 'feature_56',
                                  'feature_64', 'feature_65...
                                  'feature_11', 'feature_12', 'feature_13',
                                  'feature_15', 'feature_16', 'feature_20',
                                  'feature_21', 'feature_22', 'feature_23',
                                  'feature_24', 'feature_27', 'feature_28',
                                  'feature_32', 'feature_33', 'feature_36',
                                  'feature_37', 'feature_38', 'feature_43',
                                  'feature_45', 'feature_46', 'feature_47',
                                  'feature_50', 'feature_51', 'feature_53',
                                  'feature_54', 'feature_58', 'feature_59', ...])])

In [97]:
from xgboost import XGBClassifier

pipe = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", XGBClassifier(
        scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]),
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        eval_metric='logloss',
        random_state=42
    ))
])

In [98]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['feature_3', 'feature_4',
                                                   'feature_6', 'feature_7',
                                                   'feature_14', 'feature_19',
                                                   'feature_25', 'feature_26',
                                                   'feature_29', 'feature_30',
                                                   'feature_31', 'feature_34',
                                                   'feature_35', 'feature_39',
                                                   'feature_40', 'feature_41',
                                                   'feature_42', 'feature_44',
                                                   'feature_52', 'feature_55',
                                                   'featur...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [99]:
y_prob = pipe.predict_proba(X_test)[:,1]

In [100]:
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, y_pred_30))

0.8755230125523012

In [101]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_30)
print(cm)

[[4156  423]
 [ 172   29]]

In [102]:
from sklearn.metrics import roc_auc_score
print("ROC AUC:", roc_auc_score(y_test, y_prob))

ROC AUC: 0.6551844403229541

In [103]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_30))

# Detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred_30))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_30)
print("Confusion Matrix:\n", cm)

Accuracy: 0.8755230125523012
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.91      0.93      4579
           1       0.06      0.14      0.09       201

    accuracy                           0.88      4780
   macro avg       0.51      0.53      0.51      4780
weighted avg       0.92      0.88      0.90      4780

Confusion Matrix:
 [[4156  423]
 [ 172   29]]

In [104]:
y_prob = pipe.predict_proba(X_test)[:,1]

y_pred_30 = (y_prob >= 0.30).astype(int)

In [105]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_30))

# Detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred_30))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_30)
print("Confusion Matrix:\n", cm)

Accuracy: 0.3410041841004184
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.32      0.48      4579
           1       0.05      0.87      0.10       201

    accuracy                           0.34      4780
   macro avg       0.52      0.59      0.29      4780
weighted avg       0.94      0.34      0.46      4780

Confusion Matrix:
 [[1456 3123]
 [  27  174]]

In [106]:
from sklearn.metrics import roc_auc_score
print("ROC AUC:", roc_auc_score(y_test, y_prob))

ROC AUC: 0.6551844403229541

In [82]:
X=df.drop("Bad_label", axis=1)
y=df["Bad_label"]

In [70]:
X

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_11,feature_12,feature_13,...,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq
0,Insignia,13-Apr-15,650.0,2.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,261936.500000,2538209.0,2528846.0,4.388924e+05,18,2.767306e+05,3500000.0,3973,3978,4093.0
1,Insignia,21-Apr-15,760.0,1.0,Card Setup,14.0,1200000.0,Y,IS1,Missing,...,15377.000000,0.0,1000000.0,5.587975e+05,68,9.818650e+07,750000000.0,3970,3970,4039.0
2,Insignia,21-Apr-15,774.0,1.0,Card Setup,14.0,700000.0,Y,IS1,Missing,...,17864.000000,0.0,121523.0,1.215230e+05,1,3.400000e+06,3400000.0,3969,3970,4407.0
3,Insignia,20-Apr-15,770.0,1.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,108562.882353,0.0,3000000.0,7.238038e+05,34,1.494412e+06,4000000.0,3966,3976,4384.0
4,Insignia,Missing,721.0,3.0,Card Setup,14.0,500000.0,Y,IS1,Missing,...,1139.000000,0.0,12662938.0,1.831072e+06,2,1.000000e+03,1000.0,3955,3961,5089.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23891,Platinum Deligh,10-Dec-15,704.0,1.0,Card Setup,14.0,119000.0,Y,PD1,PD3,...,48522.500000,0.0,185000.0,7.728240e+04,16,9.814650e+04,300000.0,3716,3737,3769.0
23892,Platinum Deligh,Missing,721.0,2.0,Card Setup,14.0,35000.0,Y,PD1,PD3,...,16393.000000,0.0,27314.0,2.731400e+04,12,1.991750e+04,50000.0,3730,3761,3751.0
23893,Platinum Maxima,24-Sep-15,748.0,3.0,Card Setup,14.0,68000.0,Y,PM1,Missing,...,692.333333,0.0,20500.0,1.628033e+04,4,2.550000e+04,50000.0,3773,3814,4204.0
23894,Platinum Deligh,30-Sep-15,740.0,3.0,Card Setup,14.0,158000.0,Y,PD1,PD3,...,61793.000000,0.0,400000.0,1.243358e+05,8,9.087500e+04,450000.0,3774,3808,3934.0
23895,Titanium Deligh,06-Nov-15,688.0,1.0,Card Setup,14.0,106000.0,Y,TD1,Missing,...,225890.500000,4669.0,1150000.0,3.086915e+05,16,7.126251e+05,10000000.0,3743,3771,3805.0

In [97]:
y

0        0
1        0
2        0
3        0
4        0
        ..
23891    0
23892    0
23893    0
23894    0
23895    0
Name: Bad_label, Length: 23896, dtype: int64

Pipeline Creation

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [72]:
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from imblearn.pipeline import Pipeline

LOGISTIC REGRESSION

In [100]:

# pipe = Pipeline(steps=[
#     ("preprocess", preprocessor),    #Scaling
#     ("smote", SMOTE(random_state=42)),  # ONLY train data
#     ("model", LogisticRegression(max_iter=2000))
# ])

In [73]:
pipe = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", LogisticRegression(max_iter=2000, class_weight='balanced'))
])

In [74]:
pipe

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['feature_3', 'feature_4',
                                                   'feature_6', 'feature_7',
                                                   'feature_14', 'feature_19',
                                                   'feature_25', 'feature_26',
                                                   'feature_29', 'feature_30',
                                                   'feature_31', 'feature_34',
                                                   'feature_35', 'feature_39',
                                                   'feature_40', 'feature_41',
                                                   'feature_42', 'feature_44',
                                                   'feature_52', 'feature_55',
                                                   'featur...
                                                   'feature_20', 'feature_21',
                                                   'feature_22', 'feature_23',
                                                   'feature_24', 'feature_27',
                                                   'feature_28', 'feature_32',
                                                   'feature_33', 'feature_36',
                                                   'feature_37', 'feature_38',
                                                   'feature_43', 'feature_45',
                                                   'feature_46', 'feature_47',
                                                   'feature_50', 'feature_51',
                                                   'feature_53', 'feature_54',
                                                   'feature_58', 'feature_59', ...])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=2000))])

In [75]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['feature_3', 'feature_4',
                                                   'feature_6', 'feature_7',
                                                   'feature_14', 'feature_19',
                                                   'feature_25', 'feature_26',
                                                   'feature_29', 'feature_30',
                                                   'feature_31', 'feature_34',
                                                   'feature_35', 'feature_39',
                                                   'feature_40', 'feature_41',
                                                   'feature_42', 'feature_44',
                                                   'feature_52', 'feature_55',
                                                   'featur...
                                                   'feature_20', 'feature_21',
                                                   'feature_22', 'feature_23',
                                                   'feature_24', 'feature_27',
                                                   'feature_28', 'feature_32',
                                                   'feature_33', 'feature_36',
                                                   'feature_37', 'feature_38',
                                                   'feature_43', 'feature_45',
                                                   'feature_46', 'feature_47',
                                                   'feature_50', 'feature_51',
                                                   'feature_53', 'feature_54',
                                                   'feature_58', 'feature_59', ...])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=2000))])

In [78]:
y_prob = pipe.predict_proba(X_test)[:,1]

# Try lower threshold
y_pred_30 = (y_prob >= 0.3).astype(int)

In [79]:
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, y_pred_30))

0.8732217573221758

In [80]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_30)
print(cm)

[[4152  430]
 [ 176   22]]

In [81]:
pd.crosstab(y_test,y_pred_30)

col_0         0    1
Bad_label
0          4152  430
1           176   22

In [82]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_30))

# Detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred_30))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_30)
print("Confusion Matrix:\n", cm)

Accuracy: 0.8732217573221758
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.91      0.93      4582
           1       0.05      0.11      0.07       198

    accuracy                           0.87      4780
   macro avg       0.50      0.51      0.50      4780
weighted avg       0.92      0.87      0.90      4780

Confusion Matrix:
 [[4152  430]
 [ 176   22]]

The model achieves a Recall of 65% for defaulters, indicating that it successfully identifies a majority of high-risk customers.

However, Precision for the Bad class is low (6%), meaning a large number of good customers are incorrectly classified as risky. This may impact customer acquisition and revenue.

In [130]:
y_prob = pipe.predict_proba(X_test)[:,1]
print("ROC AUC:", roc_auc_score(y_test, y_prob))

ROC AUC: 0.5721036202267106

RANDOM FOREST

In [131]:
from sklearn.ensemble import RandomForestClassifier

In [132]:
pipe = Pipeline(steps=[
    ("preprocess", preprocessor),   #Scaling
    # ("smote", SMOTE(random_state=42)),  # ONLY train data
    ("model", RandomForestClassifier(n_estimators=200,
        random_state=42,
        class_weight="balanced"))
])

In [133]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['feature_3', 'feature_4',
                                                   'feature_7', 'feature_14',
                                                   'feature_19', 'feature_25',
                                                   'feature_26', 'feature_29',
                                                   'feature_30', 'feature_31',
                                                   'feature_34', 'feature_35',
                                                   'feature_39', 'feature_40',
                                                   'feature_41', 'feature_42',
                                                   'feature_44', 'feature_52',
                                                   'feature_55', 'feature_56',
                                                   'featu...
                                                   'feature_23', 'feature_24',
                                                   'feature_27', 'feature_28',
                                                   'feature_32', 'feature_33',
                                                   'feature_36', 'feature_37',
                                                   'feature_38', 'feature_43',
                                                   'feature_45', 'feature_46',
                                                   'feature_47', 'feature_50',
                                                   'feature_51', 'feature_53',
                                                   'feature_58', 'feature_59',
                                                   'feature_60', 'feature_62', ...])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [89]:
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, y_predict))

0.552510460251046

In [90]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
print(cm)

[[2512 2070]
 [  69  129]]

In [91]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_predict))

# Detailed classification report
print("Classification Report:\n", classification_report(y_test, y_predict))

# Confusion matrix
cm = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:\n", cm)

Accuracy: 0.552510460251046
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.55      0.70      4582
           1       0.06      0.65      0.11       198

    accuracy                           0.55      4780
   macro avg       0.52      0.60      0.40      4780
weighted avg       0.94      0.55      0.68      4780

Confusion Matrix:
 [[2512 2070]
 [  69  129]]

In [92]:
from sklearn.metrics import roc_auc_score

y_prob = pipe.predict_proba(X_test)[:,1]
print("ROC AUC:", roc_auc_score(y_test, y_prob))

ROC AUC: 0.5813581030735112