In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\aparna\anaconda3\lib\site-packages (9.6.0)

In [2]:
import mysql.connector

conn = mysql.connector.connect(
    host="18.136.157.135",
    port=3306,
    user=" dm_team1",
    password="DM!$Team&279@20!",
    database="project_banking"
)

print("Connected Successfully!")

cursor = conn.cursor()
cursor.execute("SHOW TABLES;")

for table in cursor:
    print(table)

Connected Successfully!
('Cust_Account',)
('Cust_Demographics',)
('Cust_Enquiry',)

In [3]:
cursor.execute("SELECT * FROM Cust_Account LIMIT 5;")
rows = cursor.fetchall()

for row in rows:
    print(row)

('10-Nov-15', '12265', '20-Oct-15', '6', '1', '09-Jun-13', '30-Jun-14', '05-Jul-14', '30-Sep-15', '20900', '0', '', '"""STDSTDSTDXXXXXXXXXXXXXXXSTDXXXXXXXXXXXXXXXSTD"""', '', '01-Sep-15', '01-Jul-14', '', '', '', '', '')
('10-Nov-15', '12265', '20-Oct-15', '10', '1', '25-May-12', '06-Sep-15', '', '03-Oct-15', '16201', '10390', '', '"""000000000000000000000000000000000000000000000000000000"""', '"""000000000000000000000000000XXX000000000000000000000000"""', '01-Oct-15', '01-Nov-12', '14000', '1400', '', '3', '5603')
('10-Nov-15', '12265', '20-Oct-15', '10', '1', '22-Mar-12', '31-Aug-15', '', '30-Sep-15', '41028', '34420', '', '"""000000000000000000000000000000000000000000000000000000"""', '"""000000000000000000000000000000000000000000000000000000"""', '01-Sep-15', '01-Oct-12', '', '', '', '', '')
('20-Jul-15', '15606', '09-Jul-15', '10', '1', '13-Jan-06', '', '26-Jul-07', '31-Jan-09', '93473', '0', '', '"""120090060060060030000000000000000000000000000000000000"""', '', '01-Jul-07', '01-Feb-06', '', '', '', '', '')
('20-Jul-15', '15606', '09-Jul-15', '6', '1', '18-Jan-15', '05-May-15', '', '31-May-15', '20250', '13500', '', '"""000000000000000"""', '', '01-May-15', '01-Jan-15', '', '', '', '', '')

In [4]:
import pandas as pd

df_account = pd.read_sql("SELECT * FROM Cust_Account", conn)
df_enquiry = pd.read_sql("SELECT * FROM Cust_Enquiry", conn)
df_demo = pd.read_sql("SELECT * FROM Cust_Demographics", conn)

print(df_account.head())

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4270682376.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_account = pd.read_sql("SELECT * FROM Cust_Account", conn)
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4270682376.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_enquiry = pd.read_sql("SELECT * FROM Cust_Enquiry", conn)
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4270682376.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_demo = pd.read_sql("SELECT * FROM Cust_Demographics", conn)

   dt_opened customer_no  upload_dt acct_type owner_indic  opened_dt  \
0  10-Nov-15       12265  20-Oct-15         6           1  09-Jun-13
1  10-Nov-15       12265  20-Oct-15        10           1  25-May-12
2  10-Nov-15       12265  20-Oct-15        10           1  22-Mar-12
3  20-Jul-15       15606  09-Jul-15        10           1  13-Jan-06
4  20-Jul-15       15606  09-Jul-15         6           1  18-Jan-15

  last_paymt_dt  closed_dt reporting_dt high_credit_amt  ... amt_past_due  \
0     30-Jun-14  05-Jul-14    30-Sep-15           20900  ...
1     06-Sep-15               03-Oct-15           16201  ...
2     31-Aug-15               30-Sep-15           41028  ...
3                26-Jul-07    31-Jan-09           93473  ...
4     05-May-15               31-May-15           20250  ...

                                     paymenthistory1  \
0  """STDSTDSTDXXXXXXXXXXXXXXXSTDXXXXXXXXXXXXXXXS...
1  """0000000000000000000000000000000000000000000...
2  """0000000000000000000000000000000000000000000...
3  """1200900600600600300000000000000000000000000...
4                              """000000000000000"""

                                     paymenthistory2 paymt_str_dt  \
0                                                       01-Sep-15
1  """000000000000000000000000000XXX0000000000000...    01-Oct-15
2  """0000000000000000000000000000000000000000000...    01-Sep-15
3                                                       01-Jul-07
4                                                       01-May-15

  paymt_end_dt creditlimit cashlimit rateofinterest paymentfrequency  \
0    01-Jul-14
1    01-Nov-12       14000      1400                               3
2    01-Oct-12
3    01-Feb-06
4    01-Jan-15

  actualpaymentamount
0
1                5603
2
3
4

[5 rows x 21 columns]

In [6]:
df_demo.to_csv("Cust_Demographics.csv", index=False)
df_account.to_csv("Cust_Account.csv", index=False)
df_enquiry.to_csv("Cust_Enquiry.csv", index=False)

In [7]:
import os
os.getcwd()

'C:\\Users\\APARNA\\Documents\\Client Project'

In [8]:
data1=pd.read_csv("Cust_Account.csv")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\2202858513.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  data1=pd.read_csv("Cust_Account.csv")

In [9]:
data1.head()

,dt_opened,customer_no,upload_dt,acct_type,owner_indic,opened_dt,last_paymt_dt,closed_dt,reporting_dt,high_credit_amt,...,amt_past_due,paymenthistory1,paymenthistory2,paymt_str_dt,paymt_end_dt,creditlimit,cashlimit,rateofinterest,paymentfrequency,actualpaymentamount
0,10-Nov-15,12265,20-Oct-15,6,1,09-Jun-13,30-Jun-14,05-Jul-14,30-Sep-15,20900.0,...,NaN,"""""""STDSTDSTDXXXXXXXXXXXXXXXSTDXXXXXXXXXXXXXXXS...",NaN,01-Sep-15,01-Jul-14,NaN,NaN,NaN,NaN,NaN
1,10-Nov-15,12265,20-Oct-15,10,1,25-May-12,06-Sep-15,NaN,03-Oct-15,16201.0,...,NaN,"""""""0000000000000000000000000000000000000000000...","""""""000000000000000000000000000XXX0000000000000...",01-Oct-15,01-Nov-12,14000.0,1400.0,NaN,3.0,5603.0
2,10-Nov-15,12265,20-Oct-15,10,1,22-Mar-12,31-Aug-15,NaN,30-Sep-15,41028.0,...,NaN,"""""""0000000000000000000000000000000000000000000...","""""""0000000000000000000000000000000000000000000...",01-Sep-15,01-Oct-12,NaN,NaN,NaN,NaN,NaN
3,20-Jul-15,15606,09-Jul-15,10,1,13-Jan-06,NaN,26-Jul-07,31-Jan-09,93473.0,...,NaN,"""""""1200900600600600300000000000000000000000000...",NaN,01-Jul-07,01-Feb-06,NaN,NaN,NaN,NaN,NaN
4,20-Jul-15,15606,09-Jul-15,6,1,18-Jan-15,05-May-15,NaN,31-May-15,20250.0,...,NaN,"""""""000000000000000""""""",NaN,01-May-15,01-Jan-15,NaN,NaN,NaN,NaN,NaN

In [10]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186329 entries, 0 to 186328
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_opened            186329 non-null  object
 1   customer_no          186329 non-null  int64
 2   upload_dt            186329 non-null  object
 3   acct_type            186329 non-null  int64
 4   owner_indic          186329 non-null  int64
 5   opened_dt            185874 non-null  object
 6   last_paymt_dt        160842 non-null  object
 7   closed_dt            77254 non-null   object
 8   reporting_dt         186329 non-null  object
 9   high_credit_amt      177454 non-null  float64
 10  cur_balance_amt      186329 non-null  int64
 11  amt_past_due         876 non-null     float64
 12  paymenthistory1      186329 non-null  object
 13  paymenthistory2      78505 non-null   object
 14  paymt_str_dt         186328 non-null  object
 15  paymt_end_dt         186328 non-null  object
 16  creditlimit          48852 non-null   float64
 17  cashlimit            35282 non-null   float64
 18  rateofinterest       24833 non-null   object
 19  paymentfrequency     63893 non-null   float64
 20  actualpaymentamount  41053 non-null   float64
dtypes: float64(6), int64(4), object(11)
memory usage: 29.9+ MB

In [11]:
date_cols = ["dt_opened","upload_dt","opened_dt","last_paymt_dt","closed_dt","reporting_dt"]

for col in date_cols:
    data1[col] = pd.to_datetime(data1[col], errors="coerce")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1903414949.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data1[col] = pd.to_datetime(data1[col], errors="coerce")

In [12]:
data1["opened_dt"].fillna(data1["dt_opened"], inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4198326471.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["opened_dt"].fillna(data1["dt_opened"], inplace=True)

Some missing values are meaningful.
For example, if last_paymt_dt is missing, it may mean the customer never made a payment.

If I directly fill missing values, the model cannot tell which values were originally missing. That removes useful information.

So I did two steps:

Create a flag column (never_paid_flag) that stores whether the value was missing.

Fill missing values with a logical replacement (opened_dt) so calculations can still be done.

This way:

The dataset has no missing values (good for models)

The information that the value was missing is still preserved

So the model can learn patterns like:
customers who never paid → higher risk.

In [13]:
data1["never_paid_flag"] = data1["last_paymt_dt"].isnull().astype(int)
data1["last_paymt_dt"].fillna(data1["opened_dt"], inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\552062690.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["last_paymt_dt"].fillna(data1["opened_dt"], inplace=True)

In [14]:
data1["is_active_account"] = data1["closed_dt"].isnull().astype(int)
data1["closed_dt"].fillna(data1["reporting_dt"], inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\3157574310.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["closed_dt"].fillna(data1["reporting_dt"], inplace=True)

In [15]:
data1["high_credit_amt"].fillna(0, inplace=True) # hign credit amount means Highest amount of credit customer ever used in that account

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1526886534.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["high_credit_amt"].fillna(0, inplace=True) # hign credit amount means Highest amount of credit customer ever used in that account

In [16]:
data1["amt_past_due"].fillna(0, inplace=True)
#Amount customer has not paid yet but should have paid.
#Because logically missing past due = customer has no overdue So replacing with 0 is correct.

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\199257729.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["amt_past_due"].fillna(0, inplace=True)

Missing values in creditlimit usually mean the account does not have a credit facility, not that the value is unknown.
So we fill missing values with 0 to represent “no credit limit”.

We also create a flag column (has_creditlimit) before filling so we don’t lose the original information about which values were missing.

This helps the model understand:

whether customer had credit access

how much credit they had

So we preserve information and keep data usable for modeling.

In [17]:
data1["has_creditlimit"] = data1["creditlimit"].notnull().astype(int)
data1["creditlimit"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1073089347.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["creditlimit"].fillna(0, inplace=True)

In [18]:
data1["has_cashlimit"] = data1["cashlimit"].notnull().astype(int)
data1["cashlimit"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\3146667054.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["cashlimit"].fillna(0, inplace=True)

In [19]:
data1["has_interest"] = data1["rateofinterest"].notnull().astype(int)
data1["rateofinterest"] = pd.to_numeric(data1["rateofinterest"], errors="coerce")
data1["rateofinterest"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\733417622.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["rateofinterest"].fillna(0, inplace=True)

In [20]:
data1["has_paymentfreq"] = data1["paymentfrequency"].notnull().astype(int)
data1["paymentfrequency"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\1705125091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["paymentfrequency"].fillna(0, inplace=True)

In [21]:
data1["has_payment"] = data1["actualpaymentamount"].notnull().astype(int)
data1["actualpaymentamount"].fillna(0, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\2958655560.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1["actualpaymentamount"].fillna(0, inplace=True)

In [22]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186329 entries, 0 to 186328
Data columns (total 28 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_opened            186329 non-null  datetime64[ns]
 1   customer_no          186329 non-null  int64
 2   upload_dt            186329 non-null  datetime64[ns]
 3   acct_type            186329 non-null  int64
 4   owner_indic          186329 non-null  int64
 5   opened_dt            186329 non-null  datetime64[ns]
 6   last_paymt_dt        186329 non-null  datetime64[ns]
 7   closed_dt            186329 non-null  datetime64[ns]
 8   reporting_dt         186329 non-null  datetime64[ns]
 9   high_credit_amt      186329 non-null  float64
 10  cur_balance_amt      186329 non-null  int64
 11  amt_past_due         186329 non-null  float64
 12  paymenthistory1      186329 non-null  object
 13  paymenthistory2      78505 non-null   object
 14  paymt_str_dt         186328 non-null  object
 15  paymt_end_dt         186328 non-null  object
 16  creditlimit          186329 non-null  float64
 17  cashlimit            186329 non-null  float64
 18  rateofinterest       186329 non-null  float64
 19  paymentfrequency     186329 non-null  float64
 20  actualpaymentamount  186329 non-null  float64
 21  never_paid_flag      186329 non-null  int64
 22  is_active_account    186329 non-null  int64
 23  has_creditlimit      186329 non-null  int64
 24  has_cashlimit        186329 non-null  int64
 25  has_interest         186329 non-null  int64
 26  has_paymentfreq      186329 non-null  int64
 27  has_payment          186329 non-null  int64
dtypes: datetime64[ns](6), float64(7), int64(11), object(4)
memory usage: 39.8+ MB

In [23]:
data2=pd.read_csv("Cust_Demographics.csv")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\2611541161.py:1: DtypeWarning: Columns (12,20,63) have mixed types. Specify dtype option on import or set low_memory=False.
  data2=pd.read_csv("Cust_Demographics.csv")

In [24]:
data2.head()

,dt_opened,customer_no,entry_time,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,Bad_label
0,18-Apr-15,1,13-Apr-15,Insignia,13-Apr-15,650.0,2.0,Card Setup,14.0,500000.0,...,21.0,R,NaN,NaN,0000-00-00,0.0,98332XXXXX,1.0,N,0
1,21-Apr-15,2,21-Apr-15,Insignia,21-Apr-15,760.0,1.0,Card Setup,14.0,1200000.0,...,17.0,R,NaN,NaN,0000-00-00,0.0,99455XXXXX,1.0,N,0
2,22-Apr-15,3,21-Apr-15,Insignia,21-Apr-15,774.0,1.0,Card Setup,14.0,700000.0,...,17.0,R,NaN,NaN,0000-00-00,0.0,98456XXXXX,1.0,N,0
3,25-Apr-15,4,15-Apr-15,Insignia,20-Apr-15,770.0,1.0,Card Setup,14.0,500000.0,...,21.0,R,NaN,NaN,6/15/65,1.0,98220XXXXX,1.0,N,0
4,06-May-15,5,30-Apr-15,Insignia,NaN,NaN,3.0,Card Setup,14.0,500000.0,...,13.0,R,NaN,NaN,0000-00-00,0.0,98111XXXXX,1.0,N,0

In [25]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 83 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  object
 1   customer_no  23896 non-null  int64
 2   entry_time   23881 non-null  object
 3   feature_1    23881 non-null  object
 4   feature_2    21060 non-null  object
 5   feature_3    21060 non-null  float64
 6   feature_4    23881 non-null  float64
 7   feature_5    23881 non-null  object
 8   feature_6    23881 non-null  float64
 9   feature_7    23881 non-null  float64
 10  feature_8    1261 non-null   object
 11  feature_9    1261 non-null   object
 12  feature_10   51 non-null     object
 13  feature_11   23881 non-null  object
 14  feature_12   23881 non-null  object
 15  feature_13   10892 non-null  object
 16  feature_14   16163 non-null  float64
 17  feature_15   23873 non-null  object
 18  feature_16   23869 non-null  object
 19  feature_17   1027 non-null   object
 20  feature_18   18 non-null     object
 21  feature_19   23881 non-null  float64
 22  feature_20   23896 non-null  object
 23  feature_21   23881 non-null  object
 24  feature_22   23896 non-null  object
 25  feature_23   23881 non-null  object
 26  feature_24   23256 non-null  object
 27  feature_25   23881 non-null  float64
 28  feature_26   23881 non-null  float64
 29  feature_27   20259 non-null  object
 30  feature_28   23881 non-null  object
 31  feature_29   23881 non-null  float64
 32  feature_30   23881 non-null  float64
 33  feature_31   23881 non-null  float64
 34  feature_32   23881 non-null  object
 35  feature_33   23881 non-null  object
 36  feature_34   23881 non-null  float64
 37  feature_35   23881 non-null  float64
 38  feature_36   18214 non-null  object
 39  feature_37   18214 non-null  object
 40  feature_38   18214 non-null  object
 41  feature_39   23881 non-null  float64
 42  feature_40   23881 non-null  float64
 43  feature_41   23881 non-null  float64
 44  feature_42   23881 non-null  float64
 45  feature_43   23881 non-null  object
 46  feature_44   23881 non-null  float64
 47  feature_45   10183 non-null  object
 48  feature_46   23802 non-null  object
 49  feature_47   23896 non-null  object
 50  feature_48   5497 non-null   object
 51  feature_49   104 non-null    float64
 52  feature_50   23881 non-null  object
 53  feature_51   12474 non-null  object
 54  feature_52   23881 non-null  float64
 55  feature_53   12286 non-null  object
 56  feature_54   23881 non-null  object
 57  feature_55   23881 non-null  float64
 58  feature_56   23881 non-null  float64
 59  feature_57   2393 non-null   object
 60  feature_58   23881 non-null  object
 61  feature_59   23881 non-null  object
 62  feature_60   23881 non-null  object
 63  feature_61   9 non-null      object
 64  feature_62   23881 non-null  object
 65  feature_63   23881 non-null  object
 66  feature_64   23881 non-null  float64
 67  feature_65   23881 non-null  float64
 68  feature_66   23881 non-null  float64
 69  feature_67   23881 non-null  float64
 70  feature_68   23881 non-null  float64
 71  feature_69   23881 non-null  float64
 72  feature_70   23881 non-null  object
 73  feature_71   23881 non-null  float64
 74  feature_72   23881 non-null  object
 75  feature_73   2945 non-null   object
 76  feature_74   17 non-null     float64
 77  feature_75   23881 non-null  object
 78  feature_76   23881 non-null  float64
 79  feature_77   23896 non-null  object
 80  feature_78   23881 non-null  float64
 81  feature_79   23881 non-null  object
 82  Bad_label    23896 non-null  int64
dtypes: float64(32), int64(2), object(49)
memory usage: 15.1+ MB

In [26]:
missing = data2.isnull().mean()*100
missing.sort_values(ascending=False)

feature_61    99.962337
feature_74    99.928858
feature_18    99.924674
feature_10    99.786575
feature_49    99.564781
                ...
feature_22     0.000000
feature_47     0.000000
feature_20     0.000000
feature_77     0.000000
Bad_label      0.000000
Length: 83, dtype: float64

In [27]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 83 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  object
 1   customer_no  23896 non-null  int64
 2   entry_time   23881 non-null  object
 3   feature_1    23881 non-null  object
 4   feature_2    21060 non-null  object
 5   feature_3    21060 non-null  float64
 6   feature_4    23881 non-null  float64
 7   feature_5    23881 non-null  object
 8   feature_6    23881 non-null  float64
 9   feature_7    23881 non-null  float64
 10  feature_8    1261 non-null   object
 11  feature_9    1261 non-null   object
 12  feature_10   51 non-null     object
 13  feature_11   23881 non-null  object
 14  feature_12   23881 non-null  object
 15  feature_13   10892 non-null  object
 16  feature_14   16163 non-null  float64
 17  feature_15   23873 non-null  object
 18  feature_16   23869 non-null  object
 19  feature_17   1027 non-null   object
 20  feature_18   18 non-null     object
 21  feature_19   23881 non-null  float64
 22  feature_20   23896 non-null  object
 23  feature_21   23881 non-null  object
 24  feature_22   23896 non-null  object
 25  feature_23   23881 non-null  object
 26  feature_24   23256 non-null  object
 27  feature_25   23881 non-null  float64
 28  feature_26   23881 non-null  float64
 29  feature_27   20259 non-null  object
 30  feature_28   23881 non-null  object
 31  feature_29   23881 non-null  float64
 32  feature_30   23881 non-null  float64
 33  feature_31   23881 non-null  float64
 34  feature_32   23881 non-null  object
 35  feature_33   23881 non-null  object
 36  feature_34   23881 non-null  float64
 37  feature_35   23881 non-null  float64
 38  feature_36   18214 non-null  object
 39  feature_37   18214 non-null  object
 40  feature_38   18214 non-null  object
 41  feature_39   23881 non-null  float64
 42  feature_40   23881 non-null  float64
 43  feature_41   23881 non-null  float64
 44  feature_42   23881 non-null  float64
 45  feature_43   23881 non-null  object
 46  feature_44   23881 non-null  float64
 47  feature_45   10183 non-null  object
 48  feature_46   23802 non-null  object
 49  feature_47   23896 non-null  object
 50  feature_48   5497 non-null   object
 51  feature_49   104 non-null    float64
 52  feature_50   23881 non-null  object
 53  feature_51   12474 non-null  object
 54  feature_52   23881 non-null  float64
 55  feature_53   12286 non-null  object
 56  feature_54   23881 non-null  object
 57  feature_55   23881 non-null  float64
 58  feature_56   23881 non-null  float64
 59  feature_57   2393 non-null   object
 60  feature_58   23881 non-null  object
 61  feature_59   23881 non-null  object
 62  feature_60   23881 non-null  object
 63  feature_61   9 non-null      object
 64  feature_62   23881 non-null  object
 65  feature_63   23881 non-null  object
 66  feature_64   23881 non-null  float64
 67  feature_65   23881 non-null  float64
 68  feature_66   23881 non-null  float64
 69  feature_67   23881 non-null  float64
 70  feature_68   23881 non-null  float64
 71  feature_69   23881 non-null  float64
 72  feature_70   23881 non-null  object
 73  feature_71   23881 non-null  float64
 74  feature_72   23881 non-null  object
 75  feature_73   2945 non-null   object
 76  feature_74   17 non-null     float64
 77  feature_75   23881 non-null  object
 78  feature_76   23881 non-null  float64
 79  feature_77   23896 non-null  object
 80  feature_78   23881 non-null  float64
 81  feature_79   23881 non-null  object
 82  Bad_label    23896 non-null  int64
dtypes: float64(32), int64(2), object(49)
memory usage: 15.1+ MB

In [29]:
data2["dt_opened"] = pd.to_datetime(data2["dt_opened"], errors="coerce")
data2["entry_time"] = pd.to_datetime(data2["entry_time"], errors="coerce")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\2978224859.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data2["dt_opened"] = pd.to_datetime(data2["dt_opened"], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\2978224859.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data2["entry_time"] = pd.to_datetime(data2["entry_time"], errors="coerce")

In [28]:
missing = data2.isnull().mean()*100
drop_cols = missing[missing > 60].index
data2.drop(columns=drop_cols, inplace=True)

In [30]:
const_cols = [col for col in data2.columns if data2[col].nunique() <= 1]
data2.drop(columns=const_cols, inplace=True)

In [31]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  datetime64[ns]
 1   customer_no  23896 non-null  int64
 2   entry_time   23881 non-null  datetime64[ns]
 3   feature_1    23881 non-null  object
 4   feature_2    21060 non-null  object
 5   feature_3    21060 non-null  float64
 6   feature_4    23881 non-null  float64
 7   feature_7    23881 non-null  float64
 8   feature_11   23881 non-null  object
 9   feature_12   23881 non-null  object
 10  feature_13   10892 non-null  object
 11  feature_14   16163 non-null  float64
 12  feature_15   23873 non-null  object
 13  feature_16   23869 non-null  object
 14  feature_19   23881 non-null  float64
 15  feature_20   23896 non-null  object
 16  feature_21   23881 non-null  object
 17  feature_22   23896 non-null  object
 18  feature_23   23881 non-null  object
 19  feature_24   23256 non-null  object
 20  feature_25   23881 non-null  float64
 21  feature_26   23881 non-null  float64
 22  feature_27   20259 non-null  object
 23  feature_28   23881 non-null  object
 24  feature_29   23881 non-null  float64
 25  feature_30   23881 non-null  float64
 26  feature_31   23881 non-null  float64
 27  feature_32   23881 non-null  object
 28  feature_33   23881 non-null  object
 29  feature_34   23881 non-null  float64
 30  feature_35   23881 non-null  float64
 31  feature_36   18214 non-null  object
 32  feature_37   18214 non-null  object
 33  feature_38   18214 non-null  object
 34  feature_39   23881 non-null  float64
 35  feature_40   23881 non-null  float64
 36  feature_41   23881 non-null  float64
 37  feature_42   23881 non-null  float64
 38  feature_43   23881 non-null  object
 39  feature_44   23881 non-null  float64
 40  feature_45   10183 non-null  object
 41  feature_46   23802 non-null  object
 42  feature_47   23896 non-null  object
 43  feature_50   23881 non-null  object
 44  feature_51   12474 non-null  object
 45  feature_52   23881 non-null  float64
 46  feature_53   12286 non-null  object
 47  feature_55   23881 non-null  float64
 48  feature_56   23881 non-null  float64
 49  feature_58   23881 non-null  object
 50  feature_59   23881 non-null  object
 51  feature_60   23881 non-null  object
 52  feature_62   23881 non-null  object
 53  feature_63   23881 non-null  object
 54  feature_64   23881 non-null  float64
 55  feature_65   23881 non-null  float64
 56  feature_66   23881 non-null  float64
 57  feature_67   23881 non-null  float64
 58  feature_68   23881 non-null  float64
 59  feature_69   23881 non-null  float64
 60  feature_70   23881 non-null  object
 61  feature_71   23881 non-null  float64
 62  feature_72   23881 non-null  object
 63  feature_75   23881 non-null  object
 64  feature_76   23881 non-null  float64
 65  feature_77   23896 non-null  object
 66  feature_78   23881 non-null  float64
 67  feature_79   23881 non-null  object
 68  Bad_label    23896 non-null  int64
dtypes: datetime64[ns](2), float64(29), int64(2), object(36)
memory usage: 12.6+ MB

In [32]:
# -------- NUMERIC COLUMNS --------
num_cols = data2.select_dtypes(include=["float64","int64"]).columns
data2[num_cols] = data2[num_cols].fillna(data2[num_cols].median())

In [33]:
# -------- CATEGORICAL COLUMNS --------
cat_cols = data2.select_dtypes(include="object").columns
data2[cat_cols] = data2[cat_cols].fillna("Missing")

In [34]:
# -------- DATE COLUMNS --------
date_cols = data2.select_dtypes(include="datetime64[ns]").columns
data2[date_cols] = data2[date_cols].fillna(pd.Timestamp("1900-01-01"))

In [35]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dt_opened    23896 non-null  datetime64[ns]
 1   customer_no  23896 non-null  int64
 2   entry_time   23896 non-null  datetime64[ns]
 3   feature_1    23896 non-null  object
 4   feature_2    23896 non-null  object
 5   feature_3    23896 non-null  float64
 6   feature_4    23896 non-null  float64
 7   feature_7    23896 non-null  float64
 8   feature_11   23896 non-null  object
 9   feature_12   23896 non-null  object
 10  feature_13   23896 non-null  object
 11  feature_14   23896 non-null  float64
 12  feature_15   23896 non-null  object
 13  feature_16   23896 non-null  object
 14  feature_19   23896 non-null  float64
 15  feature_20   23896 non-null  object
 16  feature_21   23896 non-null  object
 17  feature_22   23896 non-null  object
 18  feature_23   23896 non-null  object
 19  feature_24   23896 non-null  object
 20  feature_25   23896 non-null  float64
 21  feature_26   23896 non-null  float64
 22  feature_27   23896 non-null  object
 23  feature_28   23896 non-null  object
 24  feature_29   23896 non-null  float64
 25  feature_30   23896 non-null  float64
 26  feature_31   23896 non-null  float64
 27  feature_32   23896 non-null  object
 28  feature_33   23896 non-null  object
 29  feature_34   23896 non-null  float64
 30  feature_35   23896 non-null  float64
 31  feature_36   23896 non-null  object
 32  feature_37   23896 non-null  object
 33  feature_38   23896 non-null  object
 34  feature_39   23896 non-null  float64
 35  feature_40   23896 non-null  float64
 36  feature_41   23896 non-null  float64
 37  feature_42   23896 non-null  float64
 38  feature_43   23896 non-null  object
 39  feature_44   23896 non-null  float64
 40  feature_45   23896 non-null  object
 41  feature_46   23896 non-null  object
 42  feature_47   23896 non-null  object
 43  feature_50   23896 non-null  object
 44  feature_51   23896 non-null  object
 45  feature_52   23896 non-null  float64
 46  feature_53   23896 non-null  object
 47  feature_55   23896 non-null  float64
 48  feature_56   23896 non-null  float64
 49  feature_58   23896 non-null  object
 50  feature_59   23896 non-null  object
 51  feature_60   23896 non-null  object
 52  feature_62   23896 non-null  object
 53  feature_63   23896 non-null  object
 54  feature_64   23896 non-null  float64
 55  feature_65   23896 non-null  float64
 56  feature_66   23896 non-null  float64
 57  feature_67   23896 non-null  float64
 58  feature_68   23896 non-null  float64
 59  feature_69   23896 non-null  float64
 60  feature_70   23896 non-null  object
 61  feature_71   23896 non-null  float64
 62  feature_72   23896 non-null  object
 63  feature_75   23896 non-null  object
 64  feature_76   23896 non-null  float64
 65  feature_77   23896 non-null  object
 66  feature_78   23896 non-null  float64
 67  feature_79   23896 non-null  object
 68  Bad_label    23896 non-null  int64
dtypes: datetime64[ns](2), float64(29), int64(2), object(36)
memory usage: 12.6+ MB

In [36]:
data3=pd.read_csv("Cust_Enquiry.csv")

In [37]:
data3.head()

   dt_opened  customer_no  upload_dt enquiry_dt  enq_purpose    enq_amt
0  18-Apr-15            1  21-Apr-15  19-Dec-14          2.0  3500000.0
1  18-Apr-15            1  21-Apr-15  05-Mar-14          5.0   500000.0
2  18-Apr-15            1  21-Apr-15  05-Mar-14          0.0    50000.0
3  18-Apr-15            1  21-Apr-15  22-Feb-14         10.0    50000.0
4  18-Apr-15            1  21-Apr-15  11-Jun-13         10.0     1000.0

In [38]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413188 entries, 0 to 413187
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   dt_opened    413188 non-null  object
 1   customer_no  413188 non-null  int64
 2   upload_dt    413078 non-null  object
 3   enquiry_dt   413078 non-null  object
 4   enq_purpose  413078 non-null  float64
 5   enq_amt      413078 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 18.9+ MB

In [39]:
data3["dt_opened"] = pd.to_datetime(data3["dt_opened"], errors="coerce")
data3["upload_dt"] = pd.to_datetime(data3["upload_dt"], errors="coerce")
data3["enquiry_dt"] = pd.to_datetime(data3["enquiry_dt"], errors="coerce")

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4175842631.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data3["dt_opened"] = pd.to_datetime(data3["dt_opened"], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4175842631.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data3["upload_dt"] = pd.to_datetime(data3["upload_dt"], errors="coerce")
C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\4175842631.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data3["enquiry_dt"] = pd.to_datetime(data3["enquiry_dt"], errors="coerce")

In [40]:
num_cols = data3.select_dtypes(include=["float64","int64"]).columns
data3[num_cols] = data3[num_cols].fillna(data3[num_cols].median())

cat_cols = data3.select_dtypes(include="object").columns
data3[cat_cols] = data3[cat_cols].fillna("Missing")

In [41]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413188 entries, 0 to 413187
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   dt_opened    413188 non-null  datetime64[ns]
 1   customer_no  413188 non-null  int64
 2   upload_dt    413078 non-null  datetime64[ns]
 3   enquiry_dt   413078 non-null  datetime64[ns]
 4   enq_purpose  413188 non-null  float64
 5   enq_amt      413188 non-null  float64
dtypes: datetime64[ns](3), float64(2), int64(1)
memory usage: 18.9 MB

In [42]:
enq= data3.groupby("customer_no").agg(
    total_enquiries=("enquiry_dt","count"),
    avg_enq_amt=("enq_amt","mean"),
    max_enq_amt=("enq_amt","max"),
    last_enq_date=("enquiry_dt","max")
).reset_index()

In [43]:
enq.head()

   customer_no  total_enquiries   avg_enq_amt  max_enq_amt last_enq_date
0            1               18  2.767306e+05    3500000.0    2014-12-19
1            2               68  9.818650e+07  750000000.0    2015-02-11
2            3                1  3.400000e+06    3400000.0    2014-02-08
3            4               34  1.494412e+06    4000000.0    2014-03-03
4            5                2  1.000000e+03       1000.0    2012-03-28

In [44]:
enq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_no      23896 non-null  int64
 1   total_enquiries  23896 non-null  int64
 2   avg_enq_amt      23896 non-null  float64
 3   max_enq_amt      23896 non-null  float64
 4   last_enq_date    23787 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 933.6 KB

In [45]:
acc = data1.groupby("customer_no").agg(  #aggregating account table
    total_accounts=("acct_type","count"),
    total_balance=("cur_balance_amt","sum"),
    avg_balance=("cur_balance_amt","mean"),
    total_past_due=("amt_past_due","sum"),
    max_credit=("high_credit_amt","max"),
    avg_credit=("high_credit_amt","mean")
).reset_index()

In [46]:
df = data2.merge(acc, on="customer_no", how="left")

In [47]:
df = df.merge(enq, on="customer_no", how="left")

In [48]:
df.head()

,dt_opened,customer_no,entry_time,feature_1,feature_2,feature_3,feature_4,feature_7,feature_11,feature_12,...,total_accounts,total_balance,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,last_enq_date
0,2015-04-18,1,2015-04-13,Insignia,13-Apr-15,650.0,2.0,500000.0,Y,IS1,...,18,4714857,261936.500000,2538209.0,2528846.0,4.388924e+05,18,2.767306e+05,3500000.0,2014-12-19
1,2015-04-21,2,2015-04-21,Insignia,21-Apr-15,760.0,1.0,1200000.0,Y,IS1,...,2,30754,15377.000000,0.0,1000000.0,5.587975e+05,68,9.818650e+07,750000000.0,2015-02-11
2,2015-04-22,3,2015-04-21,Insignia,21-Apr-15,774.0,1.0,700000.0,Y,IS1,...,1,17864,17864.000000,0.0,121523.0,1.215230e+05,1,3.400000e+06,3400000.0,2014-02-08
3,2015-04-25,4,2015-04-15,Insignia,20-Apr-15,770.0,1.0,500000.0,Y,IS1,...,17,1845569,108562.882353,0.0,3000000.0,7.238038e+05,34,1.494412e+06,4000000.0,2014-03-03
4,2015-05-06,5,2015-04-30,Insignia,Missing,721.0,3.0,500000.0,Y,IS1,...,7,7973,1139.000000,0.0,12662938.0,1.831072e+06,2,1.000000e+03,1000.0,2012-03-28

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23896 entries, 0 to 23895
Data columns (total 79 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   dt_opened        23896 non-null  datetime64[ns]
 1   customer_no      23896 non-null  int64
 2   entry_time       23896 non-null  datetime64[ns]
 3   feature_1        23896 non-null  object
 4   feature_2        23896 non-null  object
 5   feature_3        23896 non-null  float64
 6   feature_4        23896 non-null  float64
 7   feature_7        23896 non-null  float64
 8   feature_11       23896 non-null  object
 9   feature_12       23896 non-null  object
 10  feature_13       23896 non-null  object
 11  feature_14       23896 non-null  float64
 12  feature_15       23896 non-null  object
 13  feature_16       23896 non-null  object
 14  feature_19       23896 non-null  float64
 15  feature_20       23896 non-null  object
 16  feature_21       23896 non-null  object
 17  feature_22       23896 non-null  object
 18  feature_23       23896 non-null  object
 19  feature_24       23896 non-null  object
 20  feature_25       23896 non-null  float64
 21  feature_26       23896 non-null  float64
 22  feature_27       23896 non-null  object
 23  feature_28       23896 non-null  object
 24  feature_29       23896 non-null  float64
 25  feature_30       23896 non-null  float64
 26  feature_31       23896 non-null  float64
 27  feature_32       23896 non-null  object
 28  feature_33       23896 non-null  object
 29  feature_34       23896 non-null  float64
 30  feature_35       23896 non-null  float64
 31  feature_36       23896 non-null  object
 32  feature_37       23896 non-null  object
 33  feature_38       23896 non-null  object
 34  feature_39       23896 non-null  float64
 35  feature_40       23896 non-null  float64
 36  feature_41       23896 non-null  float64
 37  feature_42       23896 non-null  float64
 38  feature_43       23896 non-null  object
 39  feature_44       23896 non-null  float64
 40  feature_45       23896 non-null  object
 41  feature_46       23896 non-null  object
 42  feature_47       23896 non-null  object
 43  feature_50       23896 non-null  object
 44  feature_51       23896 non-null  object
 45  feature_52       23896 non-null  float64
 46  feature_53       23896 non-null  object
 47  feature_55       23896 non-null  float64
 48  feature_56       23896 non-null  float64
 49  feature_58       23896 non-null  object
 50  feature_59       23896 non-null  object
 51  feature_60       23896 non-null  object
 52  feature_62       23896 non-null  object
 53  feature_63       23896 non-null  object
 54  feature_64       23896 non-null  float64
 55  feature_65       23896 non-null  float64
 56  feature_66       23896 non-null  float64
 57  feature_67       23896 non-null  float64
 58  feature_68       23896 non-null  float64
 59  feature_69       23896 non-null  float64
 60  feature_70       23896 non-null  object
 61  feature_71       23896 non-null  float64
 62  feature_72       23896 non-null  object
 63  feature_75       23896 non-null  object
 64  feature_76       23896 non-null  float64
 65  feature_77       23896 non-null  object
 66  feature_78       23896 non-null  float64
 67  feature_79       23896 non-null  object
 68  Bad_label        23896 non-null  int64
 69  total_accounts   23896 non-null  int64
 70  total_balance    23896 non-null  int64
 71  avg_balance      23896 non-null  float64
 72  total_past_due   23896 non-null  float64
 73  max_credit       23896 non-null  float64
 74  avg_credit       23896 non-null  float64
 75  total_enquiries  23896 non-null  int64
 76  avg_enq_amt      23896 non-null  float64
 77  max_enq_amt      23896 non-null  float64
 78  last_enq_date    23787 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(35), int64(5), object(36)
memory usage: 14.4+ MB

In [50]:
 today = pd.Timestamp.today()#Dates cannot go into model directly.

df["account_age_days"] = (today - df["dt_opened"]).dt.days
df["customer_tenure_days"] = (today - df["entry_time"]).dt.days
df["days_since_last_enq"] = (today - df["last_enq_date"]).dt.days

In [51]:
df["days_since_last_enq"].fillna(9999, inplace=True)

C:\Users\APARNA\AppData\Local\Temp\ipykernel_4324\2094388345.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["days_since_last_enq"].fillna(9999, inplace=True)

In [52]:
df.drop(columns=["dt_opened","entry_time","last_enq_date"], inplace=True)

In [53]:
df.drop(columns=["customer_no"], inplace=True)

In [54]:
df.columns

Index(['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_7',
       'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15',
       'feature_16', 'feature_19', 'feature_20', 'feature_21', 'feature_22',
       'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27',
       'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32',
       'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37',
       'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42',
       'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47',
       'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_55',
       'feature_56', 'feature_58', 'feature_59', 'feature_60', 'feature_62',
       'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67',
       'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72',
       'feature_75', 'feature_76', 'feature_77', 'feature_78', 'feature_79',
       'Bad_label', 'total_accounts', 'total_balance', 'avg_balance',
       'total_past_due', 'max_credit', 'avg_credit', 'total_enquiries',
       'avg_enq_amt', 'max_enq_amt', 'account_age_days',
       'customer_tenure_days', 'days_since_last_enq'],
      dtype='object')

total_accounts: How many active credit accounts customer has.
total_balance: Total outstanding balance.
avg_balance: Balance per customer
total_past_due: Total overdue amount.
max_credit: Highest credit limit across accounts.
avg_credit: Highest credit limit across accounts.
total_enquiries: Number of times customer applied for credit.
avg_enq_amount: Average requested loan amount..
max_enq_amount: Largest loan requested.
days_since_last_enq: Recency of last credit enquiry.

##EDA

In [55]:
df["Bad_label"].value_counts()
df["Bad_label"].value_counts(normalize=True)
#Dataset is highly imbalanced with only 4.2% bad customers.

Bad_label
0    0.957985
1    0.042015
Name: proportion, dtype: float64

In [56]:
df.describe()

,feature_3,feature_4,feature_7,feature_14,feature_19,feature_25,feature_26,feature_29,feature_30,feature_31,...,avg_balance,total_past_due,max_credit,avg_credit,total_enquiries,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq
count,23896.000000,23896.000000,2.389600e+04,23896.000000,23896.000000,23896.000000,23896.000000,23896.000000,23896.000000,23896.000000,...,2.389600e+04,2.389600e+04,2.389600e+04,2.389600e+04,23896.000000,2.389600e+04,2.389600e+04,23896.000000,23896.000000,23896.000000
mean,722.970581,2.322020,1.190610e+05,9.353030,1.049381,1.233763,0.725184,217552.732968,2001.186391,0.651908,...,7.082324e+04,9.469535e+02,5.712405e+05,1.374346e+05,17.286491,5.483429e+05,7.231267e+06,3821.394459,3875.574824,4010.857466
std,35.041620,0.892719,7.750007e+04,4.975764,0.216666,0.423232,1.124780,159239.881327,11.990042,2.343030,...,2.152128e+05,4.139207e+04,2.043482e+06,3.910046e+05,15.253240,3.086798e+06,4.162499e+07,68.600944,1060.110829,472.072336
min,-1.000000,1.000000,0.000000e+00,0.000000,1.000000,1.000000,0.000000,110001.000000,1964.000000,0.000000,...,-1.165763e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000e+00,1.000000e+00,3717.000000,3725.000000,3725.000000
25%,700.000000,1.000000,7.200000e+04,12.000000,1.000000,1.000000,0.000000,110051.000000,1991.000000,0.000000,...,9.083621e+03,0.000000e+00,7.043950e+04,3.914831e+04,7.000000,4.183333e+04,1.000000e+05,3762.000000,3792.000000,3853.000000
50%,721.000000,3.000000,1.040000e+05,12.000000,1.000000,1.000000,0.000000,110094.000000,2005.000000,0.000000,...,2.596633e+04,0.000000e+00,1.863780e+05,6.981382e+04,13.000000,9.055286e+04,4.000000e+05,3811.000000,3844.000000,3930.000000
75%,741.000000,3.000000,1.390000e+05,12.000000,1.000000,1.000000,2.000000,390002.000000,2011.000000,0.000000,...,6.346017e+04,0.000000e+00,4.600000e+05,1.328318e+05,23.000000,2.089790e+05,1.004940e+06,3876.000000,3904.000000,4030.000000
max,896.000000,3.000000,1.217000e+06,12.000000,2.000000,2.000000,10.000000,712245.000000,2015.000000,12.000000,...,1.172659e+07,4.869309e+06,1.800000e+08,3.366662e+07,308.000000,1.709149e+08,1.000000e+09,3976.000000,46084.000000,9999.000000

In [57]:
df.groupby("Bad_label")["total_past_due"].mean()

Bad_label
0    964.179364
1    554.191235
Name: total_past_due, dtype: float64

In [58]:
df.groupby("Bad_label")["total_enquiries"].mean()

Bad_label
0    17.296829
1    17.050797
Name: total_enquiries, dtype: float64

In [59]:
df.groupby("Bad_label")["days_since_last_enq"].mean()

Bad_label
0    4011.812991
1    3989.070717
Name: days_since_last_enq, dtype: float64

In [60]:
df['utilization_ratio'] = df['avg_balance'] / (df['max_credit'] + 1)
df['past_due_ratio'] = df['total_past_due'] / (df['max_credit'] + 1)
df['enquiry_rate'] = df['total_enquiries'] / (df['account_age_days'] + 1)
df['credit_intensity'] = df['avg_credit'] / (df['max_credit'] + 1)
df['tenure_ratio'] = df['customer_tenure_days'] / (df['account_age_days'] + 1)

In [61]:
df.corr(numeric_only=True)

,feature_3,feature_4,feature_7,feature_14,feature_19,feature_25,feature_26,feature_29,feature_30,feature_31,...,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq,utilization_ratio,past_due_ratio,enquiry_rate,credit_intensity,tenure_ratio
feature_3,1.000000,-0.244546,0.300612,0.000409,0.036544,-0.107900,0.031748,-0.013415,-0.054855,0.004234,...,0.078184,0.064036,-0.003184,-0.001691,0.130340,-0.000086,-0.013943,-0.050217,-0.125609,-0.001487
feature_4,-0.244546,1.000000,-0.092159,0.090714,-0.026393,0.028709,0.186957,-0.152153,0.036611,-0.222876,...,-0.026382,-0.020338,0.375516,0.046469,0.042988,0.008352,0.007235,0.026442,0.047615,0.022063
feature_7,0.300612,-0.092159,1.000000,-0.007433,-0.018849,-0.126479,0.086991,0.044309,-0.061531,-0.023632,...,0.105218,0.091079,0.067054,-0.000671,0.066478,-0.004694,0.015662,0.098253,-0.265242,-0.005044
feature_14,0.000409,0.090714,-0.007433,1.000000,-0.022227,0.002186,-0.005523,-0.412585,-0.031041,-0.040439,...,-0.044757,-0.037288,0.071921,0.019090,0.009058,-0.000882,-0.006790,-0.058303,0.050328,0.014432
feature_19,0.036544,-0.026393,-0.018849,-0.022227,1.000000,0.016502,-0.045115,-0.017425,0.033750,0.011191,...,0.004657,-0.008332,-0.012258,-0.006830,0.043868,-0.002526,-0.005777,-0.069883,0.048666,-0.006043
feature_25,-0.107900,0.028709,-0.126479,0.002186,0.016502,1.000000,-0.248867,-0.044356,0.054272,0.007362,...,-0.053276,-0.059211,-0.039829,-0.016409,-0.043483,-0.006084,-0.017009,-0.155038,0.198011,-0.013834
feature_26,0.031748,0.186957,0.086991,-0.005523,-0.045115,-0.248867,1.000000,0.088713,-0.029610,-0.167786,...,0.028855,0.031741,0.551933,0.018342,0.099940,0.017198,0.030730,0.084311,-0.120858,-0.017620
feature_29,-0.013415,-0.152153,0.044309,-0.412585,-0.017425,-0.044356,0.088713,1.000000,0.077398,-0.019985,...,0.041952,0.044951,-0.041371,-0.021031,-0.025972,0.000249,0.022475,0.141759,-0.148321,-0.018363
feature_30,-0.054855,0.036611,-0.061531,-0.031041,0.033750,0.054272,-0.029610,0.077398,1.000000,-0.006384,...,-0.034174,-0.029550,0.001837,0.008662,-0.038677,-0.010842,-0.000531,0.005377,0.043187,0.008555
feature_31,0.004234,-0.222876,-0.023632,-0.040439,0.011191,0.007362,-0.167786,-0.019985,-0.006384,1.000000,...,-0.005661,-0.010568,-0.377772,-0.031930,-0.056629,-0.002054,-0.006909,-0.024203,0.022419,-0.007348
feature_34,0.110020,-0.074237,0.113484,0.008497,0.029353,-0.101519,0.014501,-0.006451,-0.211073,0.026071,...,0.073052,0.047148,-0.041427,-0.017118,0.028058,-0.006084,0.004518,0.014963,-0.079144,-0.014441
feature_35,0.052250,0.004941,0.091290,-0.041926,-0.003764,-0.027017,0.057395,0.080470,0.013549,-0.022156,...,0.049629,0.030412,0.052105,0.002467,0.034197,-0.001295,0.005413,0.042077,-0.066250,-0.000928
feature_39,-0.109355,0.074801,-0.113239,-0.009130,-0.029140,0.102879,-0.013954,0.007195,0.212626,-0.027309,...,-0.072583,-0.047959,0.042341,0.017230,-0.027735,0.006124,-0.004702,-0.016564,0.079586,0.014494
feature_40,-0.077983,0.000208,-0.078877,-0.066176,-0.014977,0.081007,-0.029631,0.082182,0.156723,0.123645,...,-0.042194,-0.022855,-0.041119,-0.011827,-0.032274,0.010412,0.006103,0.004201,0.053122,-0.009165
feature_41,-0.006529,0.027442,0.013453,-0.026739,-0.037409,-0.131980,0.100491,0.069432,0.117605,-0.030032,...,-0.023499,0.009777,0.069869,0.006447,0.012974,0.008225,0.007290,0.109245,-0.092455,0.001899
feature_42,-0.041024,0.018673,-0.042683,0.004551,-0.006595,0.097925,-0.047998,-0.005961,0.051861,0.018664,...,-0.020330,-0.020870,-0.024400,-0.005520,-0.013767,-0.001826,-0.006714,-0.031885,0.047846,-0.003934
feature_44,-0.018789,-0.149460,0.039723,-0.407595,-0.018501,-0.033898,0.085234,0.983204,0.076640,-0.020972,...,0.040679,0.044195,-0.040672,-0.020030,-0.025803,-0.000108,0.021807,0.139398,-0.142583,-0.017405
feature_52,0.056958,0.062276,0.573739,0.011326,-0.039237,-0.058729,0.110838,0.049173,-0.049564,-0.047951,...,0.038373,0.049158,0.139577,0.004689,0.047349,-0.002217,-0.002426,0.117436,-0.164934,-0.004405
feature_55,0.038684,-0.026692,-0.009875,-0.026364,0.918357,-0.039841,-0.032897,-0.015149,0.038677,0.013819,...,0.006471,-0.005122,-0.010471,-0.006546,0.046274,-0.002447,-0.005095,-0.065669,0.035183,-0.005875
feature_56,0.056112,0.014438,0.024565,-0.008532,-0.007106,-0.027137,0.047401,0.088064,0.047992,-0.009880,...,0.034352,0.025909,0.004106,-0.008983,-0.001980,0.003479,0.013880,0.024016,-0.042562,-0.009261
feature_64,0.028380,0.043182,-0.000851,0.036222,-0.012418,0.004380,0.026892,-0.022602,0.141263,-0.012905,...,0.016797,0.009050,0.011021,-0.010223,-0.006599,0.006659,0.009338,-0.002126,0.007065,-0.010955
feature_65,-0.038780,0.076695,-0.056591,0.073241,-0.022052,0.028327,-0.012500,-0.152658,0.128527,-0.011119,...,-0.029978,-0.027975,-0.012062,-0.000241,-0.009096,-0.008490,-0.013510,-0.052822,0.087515,0.000544
feature_66,-0.057687,-0.073999,-0.007093,-0.241405,-0.047027,0.009110,0.042741,0.650677,0.235309,-0.026225,...,0.014180,0.018567,-0.014722,-0.019323,-0.036274,-0.001272,0.016705,0.075880,-0.036377,-0.018393
feature_67,-0.064111,0.085263,-0.060804,0.137769,-0.037576,0.071602,-0.029461,-0.200882,0.359842,-0.028672,...,-0.035047,-0.036889,0.050835,-0.007792,-0.021649,0.000984,-0.005708,-0.053137,0.121874,-0.011122
feature_68,0.110020,-0.074237,0.113484,0.008497,0.029353,-0.101519,0.014501,-0.006451,-0.211073,0.026071,...,0.073052,0.047148,-0.041427,-0.017118,0.028058,-0.006084,0.004518,0.014963,-0.079144,-0.014441
feature_69,0.052250,0.004941,0.091290,-0.041926,-0.003764,-0.027017,0.057395,0.080470,0.013549,-0.022156,...,0.049629,0.030412,0.052105,0.002467,0.034197,-0.001295,0.005413,0.042077,-0.066250,-0.000928
feature_71,0.029551,0.032572,0.000597,0.035512,-0.008847,0.023313,0.022745,-0.049596,0.033412,-0.011826,...,0.023925,0.017538,0.009269,-0.010853,0.000544,0.001709,0.008492,0.006275,-0.006895,-0.011469
feature_76,-0.008012,-0.018708,0.048119,-0.036781,0.010217,-0.013503,0.013814,0.022407,-0.010196,-0.002327,...,0.018773,0.009470,-0.001052,-0.001309,0.002512,-0.000517,0.060527,0.008191,-0.018438,-0.001244
feature_78,-0.005501,0.024352,-0.009618,-0.062174,0.003474,0.010019,0.017826,0.028278,0.051184,-0.052945,...,-0.005452,-0.004353,0.044720,-0.001922,0.012594,-0.002142,-0.005810,-0.002517,0.007818,-0.004842
Bad_label,-0.042356,0.017219,-0.059403,0.010797,0.005220,0.021835,-0.024310,-0.018638,0.006487,-0.006723,...,0.004330,-0.004213,-0.016724,0.002384,-0.009665,-0.002309,-0.002398,-0.002808,0.033220,0.003620
total_accounts,0.060161,-0.005186,0.227343,-0.083848,-0.053639,-0.205477,0.132284,0.184831,-0.087132,-0.024528,...,0.103071,0.193716,0.075138,0.008877,-0.056303,-0.011451,0.032070,0.710146,-0.610673,0.004130
total_balance,0.087909,-0.001892,0.066670,-0.047937,0.007141,-0.069024,0.038352,0.046766,-0.010718,0.007720,...,0.248717,0.181042,0.015204,-0.000347,-0.023997,-0.002813,0.007420,0.237500,-0.233003,-0.001281
avg_balance,0.119278,-0.010353,0.038982,-0.035152,0.037417,-0.036699,0.012969,0.027376,0.022911,0.014585,...,0.204669,0.108060,0.001519,-0.002865,-0.011194,-0.001793,-0.000559,0.064177,-0.134743,-0.002929
total_past_due,-0.023734,0.000599,0.033921,-0.018833,-0.003309,-0.010923,0.037638,0.021759,-0.009192,-0.005545,...,0.020751,0.009969,0.007071,-0.000132,0.000130,-0.000260,0.486410,0.027931,-0.023676,-0.000595
max_credit,0.119605,-0.014473,0.110120,-0.046772,0.014271,-0.073728,0.039062,0.042114,-0.014290,0.005593,...,0.307272,0.210500,0.015666,0.002539,-0.011540,-0.003160,0.001917,0.190077,-0.245625,0.001609
avg_credit,0.125145,-0.013638,0.082685,-0.040784,0.032232,-0.057798,0.026982,0.030840,-0.005490,0.008841,...,0.282864,0.170055,0.010268,-0.000225,-0.002721,-0.003922,-0.000238,0.106117,-0.147058,-0.000839
total_enquiries,-0.050376,0.033919,0.099182,-0.056699,-0.069762,-0.155268,0.095899,0.140175,0.005555,-0.031489,...,0.103013,0.210335,0.082664,0.014487,-0.142575,-0.010937,0.050189,0.999624,-0.467281,0.009307
avg_enq_amt,0.078184,-0.026382,0.105218,-0.044757,0.004657,-0.053276,0.028855,0.041952,-0.034174,-0.005661,...,1.000000,0.761236,0.011643,0.000583,0.005570,-0.001879,0.003936,0.102871,-0.101149,-0.000136
max_enq_amt,0.064036,-0.020338,0.091079,-0.037288,-0.008332,-0.059211,0.031741,0.044951,-0.029550,-0.010568,...,0.761236,1.000000,0.014429,0.004871,-0.004860,-0.001966,0.008416,0.210510,-0.131589,0.004025
account_age_days,-0.003184,0.375516,0.067054,0.071921,-0.012258,-0.039829,0.551933,-0.041371,0.001837,-0.377772,...,0.011643,0.014429,1.000000,0.057775,0.145031,0.003553,0.019609,0.062119,-0.075817,-0.007705
customer_tenure_days,-0.001691,0.046469,-0.000671,0.019090,-0.006830,-0.016409,0.018342,-0.021031,0.008662,-0.031930,...,0.000583,0.004871,0.057775,1.000000,0.004702,-0.000051,0.000282,0.013584,-0.005888,0.997724
days_since_last_enq,0.130340,0.042988,0.066478,0.009058,0.043868,-0.043483,0.099940,-0.025972,-0.038677,-0.056629,...,0.005570,-0.004860,0.145031,0.004702,1.000000,0.064930,-0.000206,-0.145873,0.086825,-0.004749
utilization_ratio,-0.000086,0.008352,-0.004694,-0.000882,-0.002526,-0.006084,0.017198,0.000249,-0.010842,-0.002054,...,-0.001879,-0.001966,0.003553,-0.000051,0.064930,1.000000,-0.000480,-0.010952,-0.020984,-0.000284
past_due_ratio,-0.013943,0.007235,0.015662,-0.006790,-0.005777,-0.017009,0.030730,0.022475,-0.000531,-0.006909,...,0.003936,0.008416,0.019609,0.000282,-0.000206,-0.000480,1.000000,0.049696,-0.011753,-0.000999
enquiry_rate,-0.050217,0.026442,0.098253,-0.058303,-0.069883,-0.155038,0.084311,0.141759,0.005377,-0.024203,...,0.102871,0.210510,0.062119,0.013584,-0.145873,-0.010952,0.049696,1.000000,-0.467332,0.009753
credit_intensity,-0.125609,0.047615,-0.265242,0.050328,0.048666,0.198011,-0.120858,-0.148321,0.043187,0.022419,...,-0.101149,-0.131589,-0.075817,-0.005888,0.086825,-0.020984,-0.011753,-0.467332,1.000000,-0.001119
tenure_ratio,-0.001487,0.022063,-0.005044,0.014432,-0.006043,-0.013834,-0.017620,-0.018363,0.008555,-0.007348,...,-0.000136,0.004025,-0.007705,0.997724,-0.004749,-0.000284,-0.000999,0.009753,-0.001119,1.000000

In [62]:
X=df.drop("Bad_label", axis=1)
y=df["Bad_label"]

In [63]:
X

,feature_1,feature_2,feature_3,feature_4,feature_7,feature_11,feature_12,feature_13,feature_14,feature_15,...,avg_enq_amt,max_enq_amt,account_age_days,customer_tenure_days,days_since_last_enq,utilization_ratio,past_due_ratio,enquiry_rate,credit_intensity,tenure_ratio
0,Insignia,13-Apr-15,650.0,2.0,500000.0,Y,IS1,Missing,0.0,159,...,2.767306e+05,3500000.0,3974,3979,4094.0,0.103579,1.003702,0.004528,0.173554,1.001006
1,Insignia,21-Apr-15,760.0,1.0,1200000.0,Y,IS1,Missing,0.0,91,...,9.818650e+07,750000000.0,3971,3971,4040.0,0.015377,0.000000,0.017120,0.558797,0.999748
2,Insignia,21-Apr-15,774.0,1.0,700000.0,Y,IS1,Missing,0.0,91,...,3.400000e+06,3400000.0,3970,3971,4408.0,0.147000,0.000000,0.000252,0.999992,1.000000
3,Insignia,20-Apr-15,770.0,1.0,500000.0,Y,IS1,Missing,0.0,157,...,1.494412e+06,4000000.0,3967,3977,4385.0,0.036188,0.000000,0.008569,0.241268,1.002268
4,Insignia,Missing,721.0,3.0,500000.0,Y,IS1,Missing,0.0,100,...,1.000000e+03,1000.0,3956,3962,5090.0,0.000090,0.000000,0.000505,0.144601,1.001264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23891,Platinum Deligh,10-Dec-15,704.0,1.0,119000.0,Y,PD1,PD3,12.0,SA05,...,9.814650e+04,300000.0,3717,3738,3770.0,0.262282,0.000000,0.004303,0.417740,1.005379
23892,Platinum Deligh,Missing,721.0,2.0,35000.0,Y,PD1,PD3,12.0,SA03,...,1.991750e+04,50000.0,3731,3762,3752.0,0.600146,0.000000,0.003215,0.999963,1.008039
23893,Platinum Maxima,24-Sep-15,748.0,3.0,68000.0,Y,PM1,Missing,12.0,CD01,...,2.550000e+04,50000.0,3774,3815,4205.0,0.033771,0.000000,0.001060,0.794124,1.010596
23894,Platinum Deligh,30-Sep-15,740.0,3.0,158000.0,Y,PD1,PD3,12.0,SA40,...,9.087500e+04,450000.0,3775,3809,3935.0,0.154482,0.000000,0.002119,0.310839,1.008739
23895,Titanium Deligh,06-Nov-15,688.0,1.0,106000.0,Y,TD1,Missing,0.0,SA03,...,7.126251e+05,10000000.0,3744,3772,3806.0,0.196426,0.004060,0.004272,0.268427,1.007210

In [64]:
y

0        0
1        0
2        0
3        0
4        0
        ..
23891    0
23892    0
23893    0
23894    0
23895    0
Name: Bad_label, Length: 23896, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [69]:
numeric_cols = X.select_dtypes(include=['int64','float64']).columns
categorical_cols = X.select_dtypes(include=['object']).columns

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [71]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

In [72]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['feature_3', 'feature_4', 'feature_7', 'feature_14', 'feature_19',
       'feature_25', 'feature_26', 'feature_29', 'feature_30', 'feature_31',
       'feature_34', 'feature_35', 'feature_39', 'feature_40', 'feature_41',
       'feature_42', 'feature_44', 'feature_52', 'feature_55', 'feature_56',
       'feature_64', 'feature_65', 'fea...
       'feature_23', 'feature_24', 'feature_27', 'feature_28', 'feature_32',
       'feature_33', 'feature_36', 'feature_37', 'feature_38', 'feature_43',
       'feature_45', 'feature_46', 'feature_47', 'feature_50', 'feature_51',
       'feature_53', 'feature_58', 'feature_59', 'feature_60', 'feature_62',
       'feature_63', 'feature_70', 'feature_72', 'feature_75', 'feature_77',
       'feature_79'],
      dtype='object'))])

In [73]:
from xgboost import XGBClassifier

pipe = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", XGBClassifier(
        scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]),
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        eval_metric='logloss',
        random_state=42
    ))
])

In [74]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['feature_3', 'feature_4', 'feature_7', 'feature_14', 'feature_19',
       'feature_25', 'feature_26', 'feature_29', 'feature_30', 'feature_31',
       'feature_34', 'feature_35', 'feature_39', 'feature_40', 'feature_41',
       'feature_42', 'feature_44', 'feature_52', 'feature_55', 'feature_56',...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [75]:
y_prob = pipe.predict_proba(X_test)[:,1]

y_pred_30 = (y_prob >= 0.30).astype(int)

In [77]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_30))

# Detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred_30))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_30)
print("Confusion Matrix:\n", cm)

Accuracy: 0.3410041841004184
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.32      0.48      4579
           1       0.05      0.87      0.10       201

    accuracy                           0.34      4780
   macro avg       0.52      0.59      0.29      4780
weighted avg       0.94      0.34      0.46      4780

Confusion Matrix:
 [[1456 3123]
 [  27  174]]

The model achieves a Recall of 87% for defaulters, indicating that it successfully identifies a majority of high-risk customers.

However, Precision for the Bad class is low (5%), meaning a large number of good customers are incorrectly classified as risky. This may impact customer acquisition and revenue.

In [84]:
from sklearn.metrics import roc_auc_score

AUC = roc_auc_score(y_test, y_prob)
print("AUC:", AUC)

AUC: 0.6551844403229541

In [85]:
gini = (2 * AUC) - 1
print("Gini:", gini)

Gini: 0.3103688806459082

In [86]:
import pandas as pd

df_test = X_test.copy()
df_test['Actual'] = y_test
df_test['Prob'] = y_prob

df_test['Decile'] = pd.qcut(df_test['Prob'], 10, labels=False)

rank_table = df_test.groupby('Decile').agg(
    Avg_Prob=('Prob', 'mean'),
    Bad_Rate=('Actual', 'mean'),
    Count=('Actual', 'count')
).sort_index(ascending=False)

rank_table

        Avg_Prob  Bad_Rate  Count
Decile
9       0.659671  0.075314    478
8       0.567253  0.075314    478
7       0.504525  0.054393    478
6       0.453854  0.064854    478
5       0.407037  0.033473    478
4       0.362218  0.033473    478
3       0.318587  0.033473    478
2       0.271289  0.020921    478
1       0.214474  0.023013    478
0       0.127561  0.006276    478

The final XGBoost model achieved a ROC-AUC of 0.655 and a Gini coefficient of 31%. This demonstrates reasonable discriminatory power in distinguishing defaulters from non-defaulters. The model shows strong rank ordering and meaningful improvement through feature engineering. Additional bureau depth and behavioral variables may further enhance discrimination.